// Generated from group_traits/trait_banks/behavior/defense_behavior_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { BehaviorTrait } from '../../../types/traits/trait';
import { Role, Rarity, BehaviorType } from '../../../types/core';

export const DEFENSE_BEHAVIOR_TRAITS = [
    {
      "name": "Protective Formation",
      "description": "Particles form protective formations",
      "rarityTier": "Common",
      "role": "DEFENSE",
      "type": "Defensive",
      "physicsLogic": {
        "strength": 0.7,
        "range": 12,
        "priority": 0.8,
        "persistence": 0.9,
        "frequency": 0.2,
        "additionalParameters": {
          "protectionRadius": 15,
          "formationDensity": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "shield_glow",
        "trailEffect": "none",
        "colorModulation": false
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reactive Defense",
          "Barrier Generation"
        ]
      }
    },
    {
      "name": "Reactive Defense",
      "description": "Particles react to threats with defensive movements",
      "rarityTier": "Uncommon",
      "role": "DEFENSE",
      "type": "Defensive",
      "physicsLogic": {
        "strength": 0.75,
        "range": 15,
        "priority": 0.85,
        "persistence": 0.85,
        "frequency": 0.3,
        "additionalParameters": {
          "reactionSpeed": 0.8,
          "threatAssessment": 0.7
        }
      },
      "visualEffects": {
        "particleEffect": "reactive_pulse",
        "trailEffect": "defense_trail",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Barrier Generation",
          "Absorption Field"
        ]
      }
    },
    {
      "name": "Barrier Generation",
      "description": "Particles generate energy barriers",
      "rarityTier": "Rare",
      "role": "DEFENSE",
      "type": "Defensive",
      "physicsLogic": {
        "strength": 0.8,
        "range": 18,
        "priority": 0.9,
        "persistence": 0.9,
        "frequency": 0.25,
        "additionalParameters": {
          "barrierStrength": 0.9,
          "barrierRegeneration": 0.7
        }
      },
      "visualEffects": {
        "particleEffect": "barrier_field",
        "trailEffect": "energy_boundary",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Absorption Field",
          "Deflection Matrix"
        ]
      }
    },
    {
      "name": "Absorption Field",
      "description": "Particles absorb and neutralize energy",
      "rarityTier": "Rare",
      "role": "DEFENSE",
      "type": "Defensive",
      "physicsLogic": {
        "strength": 0.85,
        "range": 20,
        "priority": 0.95,
        "persistence": 0.95,
        "frequency": 0.2,
        "additionalParameters": {
          "absorptionRate": 0.8,
          "energyCapacity": 0.9
        }
      },
      "visualEffects": {
        "particleEffect": "absorption_glow",
        "trailEffect": "energy_intake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Deflection Matrix",
          "Temporal Shield"
        ]
      }
    },
    {
      "name": "Deflection Matrix",
      "description": "Particles deflect incoming forces",
      "rarityTier": "Epic",
      "role": "DEFENSE",
      "type": "Defensive",
      "physicsLogic": {
        "strength": 0.9,
        "range": 25,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.15,
        "additionalParameters": {
          "deflectionAngle": 175,
          "deflectionEfficiency": 0.9
        }
      },
      "visualEffects": {
        "particleEffect": "deflection_ripple",
        "trailEffect": "force_redirection",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Shield",
          "Quantum Barrier"
        ]
      }
    },
    {
      "name": "Temporal Shield",
      "description": "Particles create shields that manipulate time",
      "rarityTier": "Epic",
      "role": "DEFENSE",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 0.95,
        "range": 30,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.1,
        "additionalParameters": {
          "timeSlowFactor": 0.2,
          "temporalBubbleRadius": 15
        }
      },
      "visualEffects": {
        "particleEffect": "time_distortion",
        "trailEffect": "temporal_boundary",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Barrier",
          "Reality Anchor"
        ]
      }
    },
    {
      "name": "Quantum Barrier",
      "description": "Particles create barriers with quantum properties",
      "rarityTier": "Legendary",
      "role": "DEFENSE",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1,
        "range": 35,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.05,
        "additionalParameters": {
          "quantumStates": 5,
          "probabilityField": 0.9
        }
      },
      "visualEffects": {
        "particleEffect": "quantum_shift",
        "trailEffect": "probability_field",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Anchor",
          "Dimensional Fortress"
        ]
      }
    },
    {
      "name": "Reality Anchor",
      "description": "Particles anchor reality to prevent distortions",
      "rarityTier": "Legendary",
      "role": "DEFENSE",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.05,
        "range": 40,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.03,
        "additionalParameters": {
          "realityStabilization": 0.95,
          "dimensionalLocking": 0.9
        }
      },
      "visualEffects": {
        "particleEffect": "reality_anchor",
        "trailEffect": "dimensional_lock",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Fortress",
          "Cosmic Aegis"
        ]
      }
    },
    {
      "name": "Dimensional Fortress",
      "description": "Particles create an impenetrable fortress across dimensions",
      "rarityTier": "Mythic",
      "role": "DEFENSE",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.1,
        "range": 45,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.02,
        "additionalParameters": {
          "dimensionalLayers": 7,
          "fortressStrength": 1
        }
      },
      "visualEffects": {
        "particleEffect": "dimensional_shift",
        "trailEffect": "fortress_boundary",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Aegis"
        ]
      }
    },
    {
      "name": "Cosmic Aegis",
      "description": "Particles create a shield that harnesses cosmic forces",
      "rarityTier": "Mythic",
      "role": "DEFENSE",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.2,
        "range": 50,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.01,
        "additionalParameters": {
          "cosmicProtection": 1,
          "universalShielding": 0.95
        }
      },
      "visualEffects": {
        "particleEffect": "cosmic_barrier",
        "trailEffect": "stellar_shield",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Fortress"
        ]
      }
    }
  ];

export default DEFENSE_BEHAVIOR_TRAITS;





