// Generated from group_traits/trait_banks/formation/defense_formation_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { FormationTrait } from '../../../types/traits/trait';
import { Role, Rarity, FalloffType } from '../../../types/core';

export const DEFENSE_FORMATION_TRAITS = [
    {
      "name": "Shield Wall",
      "description": "Particles form a protective wall",
      "rarityTier": "Common",
      "role": "DEFENSE",
      "pattern": "shieldWallPattern",
      "physicsLogic": {
        "stiffness": 0.8,
        "range": 10,
        "falloff": "linear",
        "targetFunction": "shieldWallPositions",
        "additionalParameters": {
          "wallWidth": 20,
          "wallHeight": 15,
          "wallThickness": 2
        }
      },
      "visualProperties": {
        "baseColor": "#33cc33",
        "particleScale": 1,
        "trailEffect": false
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dome Shield",
          "Barrier Matrix"
        ]
      }
    },
    {
      "name": "Dome Shield",
      "description": "Particles form a protective dome",
      "rarityTier": "Uncommon",
      "role": "DEFENSE",
      "pattern": "domeShieldPattern",
      "physicsLogic": {
        "stiffness": 0.75,
        "range": 12,
        "falloff": "quadratic",
        "targetFunction": "domeShieldPositions",
        "additionalParameters": {
          "domeRadius": 15,
          "domeDensity": 0.8
        }
      },
      "visualProperties": {
        "baseColor": "#55dd55",
        "particleScale": 0.95,
        "trailEffect": false
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Barrier Matrix",
          "Orbital Defense"
        ]
      }
    },
    {
      "name": "Barrier Matrix",
      "description": "Particles form an interlocking barrier matrix",
      "rarityTier": "Rare",
      "role": "DEFENSE",
      "pattern": "barrierMatrixPattern",
      "physicsLogic": {
        "stiffness": 0.7,
        "range": 15,
        "falloff": "linear",
        "targetFunction": "barrierMatrixPositions",
        "additionalParameters": {
          "matrixSize": [
            18,
            18,
            5
          ],
          "cellSize": 3
        }
      },
      "visualProperties": {
        "baseColor": "#77ee77",
        "particleScale": 0.9,
        "trailEffect": false
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Orbital Defense",
          "Reactive Armor"
        ]
      }
    },
    {
      "name": "Orbital Defense",
      "description": "Particles orbit to form a dynamic defense",
      "rarityTier": "Rare",
      "role": "DEFENSE",
      "pattern": "orbitalDefensePattern",
      "physicsLogic": {
        "stiffness": 0.65,
        "range": 18,
        "falloff": "inverse",
        "targetFunction": "orbitalDefensePositions",
        "additionalParameters": {
          "orbitRadius": 12,
          "orbitLayers": 3,
          "rotationSpeed": 0.4
        }
      },
      "visualProperties": {
        "baseColor": "#99ff99",
        "particleScale": 0.85,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reactive Armor",
          "Absorption Field"
        ]
      }
    },
    {
      "name": "Reactive Armor",
      "description": "Particles form armor that reacts to threats",
      "rarityTier": "Epic",
      "role": "DEFENSE",
      "pattern": "reactiveArmorPattern",
      "physicsLogic": {
        "stiffness": 0.6,
        "range": 20,
        "falloff": "exponential",
        "targetFunction": "reactiveArmorPositions",
        "additionalParameters": {
          "armorThickness": 4,
          "reactionSpeed": 0.6,
          "coverageArea": 0.8
        }
      },
      "visualProperties": {
        "baseColor": "#aaffaa",
        "particleScale": 0.8,
        "trailEffect": false
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Absorption Field",
          "Temporal Barrier"
        ]
      }
    },
    {
      "name": "Absorption Field",
      "description": "Particles form a field that absorbs energy",
      "rarityTier": "Epic",
      "role": "DEFENSE",
      "pattern": "absorptionFieldPattern",
      "physicsLogic": {
        "stiffness": 0.55,
        "range": 25,
        "falloff": "quadratic",
        "targetFunction": "absorptionFieldPositions",
        "additionalParameters": {
          "fieldRadius": 15,
          "absorptionRate": 0.7,
          "fieldDensity": 0.6
        }
      },
      "visualProperties": {
        "baseColor": "#bbffbb",
        "particleScale": 0.75,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Barrier",
          "Quantum Shield"
        ]
      }
    },
    {
      "name": "Temporal Barrier",
      "description": "Particles form a barrier that slows time",
      "rarityTier": "Legendary",
      "role": "DEFENSE",
      "pattern": "temporalBarrierPattern",
      "physicsLogic": {
        "stiffness": 0.5,
        "range": 30,
        "falloff": "exponential",
        "targetFunction": "temporalBarrierPositions",
        "additionalParameters": {
          "barrierThickness": 5,
          "timeSlowFactor": 0.3,
          "temporalField": 18
        }
      },
      "visualProperties": {
        "baseColor": "#ccffcc",
        "particleScale": 0.7,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Shield",
          "Dimensional Fortress"
        ]
      }
    },
    {
      "name": "Quantum Shield",
      "description": "Particles form a shield with quantum properties",
      "rarityTier": "Legendary",
      "role": "DEFENSE",
      "pattern": "quantumShieldPattern",
      "physicsLogic": {
        "stiffness": 0.45,
        "range": 35,
        "falloff": "quantum",
        "targetFunction": "quantumShieldPositions",
        "additionalParameters": {
          "shieldRadius": 20,
          "quantumStates": 5,
          "phaseShiftRate": 0.4
        }
      },
      "visualProperties": {
        "baseColor": "#ddffdd",
        "particleScale": 0.65,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Fortress",
          "Reality Bastion"
        ]
      }
    },
    {
      "name": "Dimensional Fortress",
      "description": "Particles form a fortress that exists across dimensions",
      "rarityTier": "Mythic",
      "role": "DEFENSE",
      "pattern": "dimensionalFortressPattern",
      "physicsLogic": {
        "stiffness": 0.4,
        "range": 40,
        "falloff": "quantum",
        "targetFunction": "dimensionalFortressPositions",
        "additionalParameters": {
          "fortressSize": 25,
          "dimensionalLayers": 4,
          "phaseShift": 0.5
        }
      },
      "visualProperties": {
        "baseColor": "#eeffee",
        "particleScale": 0.6,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Bastion"
        ]
      }
    },
    {
      "name": "Reality Bastion",
      "description": "Particles form an impenetrable bastion of reality",
      "rarityTier": "Mythic",
      "role": "DEFENSE",
      "pattern": "realityBastionPattern",
      "physicsLogic": {
        "stiffness": 0.35,
        "range": 45,
        "falloff": "quantum",
        "targetFunction": "realityBastionPositions",
        "additionalParameters": {
          "bastionRadius": 30,
          "realityWarpFactor": 0.9,
          "impenetrabilityFactor": 0.95
        }
      },
      "visualProperties": {
        "baseColor": "#ffffff",
        "particleScale": 0.55,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Fortress"
        ]
      }
    }
  ];

export default DEFENSE_FORMATION_TRAITS;





