// Generated from group_traits/trait_banks/subclass/defense_subclass_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { SubclassTrait } from '../../../types/traits/trait';
import { Role, Rarity, AbilityType } from '../../../types/core';

export const DEFENSE_SUBCLASS_TRAITS = [
    {
      "name": "Guardian",
      "description": "A stalwart defender that creates protective barriers",
      "rarityTier": "Common",
      "role": "DEFENSE",
      "formationTrait": "Shield Wall",
      "abilities": [
        {
          "name": "Barrier Formation",
          "description": "Creates a solid barrier to block incoming threats",
          "type": "Primary",
          "cooldown": 5,
          "physicsLogic": {
            "forceMultiplier": 1.2,
            "rangeMultiplier": 1.5,
            "durationSeconds": 6
          },
          "visualEffects": {
            "particleEffect": "barrier_glow",
            "areaEffect": "shield_wall",
            "colorFlash": "#33cc33"
          }
        },
        {
          "name": "Fortify",
          "description": "Strengthens existing barriers",
          "type": "Secondary",
          "cooldown": 8,
          "physicsLogic": {
            "forceMultiplier": 1.4,
            "rangeMultiplier": 1.2,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "reinforcement_pulse",
            "areaEffect": "fortification_grid",
            "colorFlash": "#55dd55"
          }
        }
      ],
      "synergy": "Works well with Core subclasses for enhanced stability",
      "themeProperties": {
        "primaryColor": "#33cc33",
        "secondaryColor": "#55dd55",
        "particleEffect": "shield_shimmer",
        "soundEffect": "barrier_hum"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Sentinel",
          "Absorber"
        ]
      }
    },
    {
      "name": "Sentinel",
      "description": "A vigilant defender that reacts to threats",
      "rarityTier": "Uncommon",
      "role": "DEFENSE",
      "formationTrait": "Dome Shield",
      "abilities": [
        {
          "name": "Reactive Defense",
          "description": "Automatically responds to incoming threats",
          "type": "Primary",
          "cooldown": 6,
          "physicsLogic": {
            "forceMultiplier": 1.3,
            "rangeMultiplier": 1.6,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "reactive_flash",
            "areaEffect": "defense_grid",
            "colorFlash": "#77ee77"
          }
        },
        {
          "name": "Vigilance",
          "description": "Increases awareness and response time",
          "type": "Secondary",
          "cooldown": 10,
          "physicsLogic": {
            "forceMultiplier": 1.2,
            "rangeMultiplier": 1.8,
            "durationSeconds": 7
          },
          "visualEffects": {
            "particleEffect": "vigilance_pulse",
            "areaEffect": "awareness_field",
            "colorFlash": "#99ff99"
          }
        }
      ],
      "synergy": "Works well with Control subclasses for coordinated defense",
      "themeProperties": {
        "primaryColor": "#77ee77",
        "secondaryColor": "#99ff99",
        "particleEffect": "vigilant_glow",
        "soundEffect": "alert_ping"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Absorber",
          "Deflector"
        ]
      }
    },
    {
      "name": "Absorber",
      "description": "A defender that absorbs and neutralizes energy",
      "rarityTier": "Rare",
      "role": "DEFENSE",
      "formationTrait": "Barrier Matrix",
      "abilities": [
        {
          "name": "Energy Absorption",
          "description": "Absorbs incoming energy attacks",
          "type": "Primary",
          "cooldown": 7,
          "physicsLogic": {
            "forceMultiplier": 1.1,
            "rangeMultiplier": 1.7,
            "durationSeconds": 6
          },
          "visualEffects": {
            "particleEffect": "absorption_field",
            "areaEffect": "energy_sink",
            "colorFlash": "#aaffaa"
          }
        },
        {
          "name": "Conversion",
          "description": "Converts absorbed energy to strengthen defenses",
          "type": "Secondary",
          "cooldown": 12,
          "physicsLogic": {
            "forceMultiplier": 1.5,
            "rangeMultiplier": 1.4,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "conversion_pulse",
            "areaEffect": "reinforced_barrier",
            "colorFlash": "#bbffbb"
          }
        }
      ],
      "synergy": "Works well with Attack subclasses for energy recycling",
      "themeProperties": {
        "primaryColor": "#aaffaa",
        "secondaryColor": "#bbffbb",
        "particleEffect": "absorption_glow",
        "soundEffect": "energy_drain"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Deflector",
          "Temporal Guardian"
        ]
      }
    }
  ];

export default DEFENSE_SUBCLASS_TRAITS;





