// Generated from group_traits/trait_banks/visual/defense_visual_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { VisualTrait } from '../../../types/traits/trait';
import { Role, Rarity } from '../../../types/core';

export const DEFENSE_VISUAL_TRAITS: VisualTrait[] = [
    {
      "id": "defense_visual_shield",
      "name": "Shield",
      "description": "A shield-shaped visual trait that enhances defensive abilities.",
      "shape": "Shield",
      "colorScheme": "Green Gradient",
      "visualEffect": "Protective Aura",
      "rarityTier": "Common",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "CustomShieldGeometry",
        "material": "MeshStandardMaterial",
        "scale": 1.1,
        "emissive": false,
        "opacity": 1,
        "colorHex": "#33cc33"
      },
      "animationProperties": {
        "pulseRate": 0.1,
        "rotationSpeed": 0,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dome",
          "Reinforced Shield"
        ]
      }
    },
    {
      "shape": "Dome",
      "colorScheme": "Emerald",
      "visualEffect": "Barrier Glow",
      "rarityTier": "Uncommon",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "HemisphereGeometry",
        "material": "MeshStandardMaterial",
        "scale": 1.15,
        "emissive": true,
        "opacity": 0.9,
        "colorHex": "#55dd55"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.1,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Barrier",
          "Energy Dome"
        ]
      }
    },
    {
      "shape": "Barrier",
      "colorScheme": "Jade",
      "visualEffect": "Force Field",
      "rarityTier": "Rare",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "BoxGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.2,
        "emissive": true,
        "opacity": 0.85,
        "colorHex": "#77ee77"
      },
      "animationProperties": {
        "pulseRate": 0.3,
        "rotationSpeed": 0,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Orbital Shield",
          "Matrix Barrier"
        ]
      }
    },
    {
      "shape": "Orbital Shield",
      "colorScheme": "Mint",
      "visualEffect": "Rotating Defense",
      "rarityTier": "Rare",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "CustomOrbitalShieldGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.25,
        "emissive": true,
        "opacity": 0.8,
        "colorHex": "#99ff99"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.4,
        "trailLength": 0.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reactive Armor",
          "Absorption Field"
        ]
      }
    },
    {
      "shape": "Reactive Armor",
      "colorScheme": "Forest",
      "visualEffect": "Adaptive Plates",
      "rarityTier": "Epic",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "CustomArmorGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.3,
        "emissive": true,
        "opacity": 0.9,
        "colorHex": "#aaffaa"
      },
      "animationProperties": {
        "pulseRate": 0.4,
        "rotationSpeed": 0.2,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Absorption Field",
          "Temporal Barrier"
        ]
      }
    },
    {
      "shape": "Absorption Field",
      "colorScheme": "Seafoam",
      "visualEffect": "Energy Sink",
      "rarityTier": "Epic",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "SphereGeometry",
        "material": "ShaderMaterial",
        "scale": 1.35,
        "emissive": true,
        "opacity": 0.75,
        "colorHex": "#bbffbb"
      },
      "animationProperties": {
        "pulseRate": 0.5,
        "rotationSpeed": 0.1,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Barrier",
          "Quantum Shield"
        ]
      }
    },
    {
      "shape": "Temporal Barrier",
      "colorScheme": "Chrono Green",
      "visualEffect": "Time Distortion",
      "rarityTier": "Legendary",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "CustomTemporalGeometry",
        "material": "ShaderMaterial",
        "scale": 1.4,
        "emissive": true,
        "opacity": 0.7,
        "colorHex": "#ccffcc"
      },
      "animationProperties": {
        "pulseRate": 0.6,
        "rotationSpeed": 0.3,
        "trailLength": 0.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Shield",
          "Reality Anchor"
        ]
      }
    },
    {
      "shape": "Quantum Shield",
      "colorScheme": "Quantum Green",
      "visualEffect": "Probability Field",
      "rarityTier": "Legendary",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "CustomQuantumGeometry",
        "material": "ShaderMaterial",
        "scale": 1.45,
        "emissive": true,
        "opacity": 0.65,
        "colorHex": "#ddffdd"
      },
      "animationProperties": {
        "pulseRate": 0.7,
        "rotationSpeed": 0.2,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Anchor",
          "Dimensional Fortress"
        ]
      }
    },
    {
      "shape": "Reality Anchor",
      "colorScheme": "Ethereal Green",
      "visualEffect": "Reality Stabilization",
      "rarityTier": "Mythic",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "CustomAnchorGeometry",
        "material": "ShaderMaterial",
        "scale": 1.5,
        "emissive": true,
        "opacity": 0.6,
        "colorHex": "#eeffee"
      },
      "animationProperties": {
        "pulseRate": 0.8,
        "rotationSpeed": 0.1,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Fortress",
          "Cosmic Aegis"
        ]
      }
    },
    {
      "shape": "Cosmic Aegis",
      "colorScheme": "Cosmic Green",
      "visualEffect": "Universal Protection",
      "rarityTier": "Mythic",
      "role": "DEFENSE",
      "renderingProperties": {
        "geometry": "CustomAegisGeometry",
        "material": "ShaderMaterial",
        "scale": 1.55,
        "emissive": true,
        "opacity": 0.55,
        "colorHex": "#ffffff"
      },
      "animationProperties": {
        "pulseRate": 0.9,
        "rotationSpeed": 0,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Fortress",
          "Reality Anchor"
        ]
      }
    }
  ];

export default DEFENSE_VISUAL_TRAITS;





