// Generated from group_traits/trait_banks/class_bonus/core_class_bonus_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { ClassBonusTrait } from '../../../types/traits/trait';
import { Role, Rarity } from '../../../types/core';

export const CORE_CLASS_BONUS_TRAITS = [
    {
      "name": "Core Stability",
      "description": "Increases stability of core particles",
      "rarityTier": "Common",
      "role": "CORE",
      "statType": "Stability",
      "bonusAmount": 15,
      "physicsLogic": {
        "forceMultiplier": 1,
        "rangeMultiplier": 1,
        "speedMultiplier": 1,
        "stabilityMultiplier": 1.15
      },
      "visualEffects": {
        "particleGlow": false,
        "particleSize": 1,
        "particleColor": "#3366cc"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Enhanced Gravity",
          "Energy Efficiency"
        ]
      }
    },
    {
      "name": "Enhanced Gravity",
      "description": "Increases gravitational pull of core particles",
      "rarityTier": "Uncommon",
      "role": "CORE",
      "statType": "Gravity",
      "bonusAmount": 20,
      "physicsLogic": {
        "forceMultiplier": 1.2,
        "rangeMultiplier": 1.1,
        "speedMultiplier": 1,
        "stabilityMultiplier": 1
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1.05,
        "particleColor": "#5588dd"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Energy Efficiency",
          "Harmonic Resonance"
        ]
      }
    },
    {
      "name": "Energy Efficiency",
      "description": "Increases energy efficiency of core particles",
      "rarityTier": "Rare",
      "role": "CORE",
      "statType": "Energy",
      "bonusAmount": 25,
      "physicsLogic": {
        "forceMultiplier": 1.1,
        "rangeMultiplier": 1.1,
        "speedMultiplier": 1.1,
        "stabilityMultiplier": 1.1
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1,
        "particleColor": "#6699ee"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Harmonic Resonance",
          "Quantum Coherence"
        ]
      }
    },
    {
      "name": "Harmonic Resonance",
      "description": "Core particles resonate harmonically",
      "rarityTier": "Rare",
      "role": "CORE",
      "statType": "Resonance",
      "bonusAmount": 30,
      "physicsLogic": {
        "forceMultiplier": 1.15,
        "rangeMultiplier": 1.15,
        "speedMultiplier": 1,
        "stabilityMultiplier": 1.15
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1.1,
        "particleColor": "#77aaff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Coherence",
          "Temporal Stability"
        ]
      }
    },
    {
      "name": "Quantum Coherence",
      "description": "Core particles maintain quantum coherence",
      "rarityTier": "Epic",
      "role": "CORE",
      "statType": "Coherence",
      "bonusAmount": 35,
      "physicsLogic": {
        "forceMultiplier": 1.2,
        "rangeMultiplier": 1.2,
        "speedMultiplier": 1.1,
        "stabilityMultiplier": 1.2
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1.15,
        "particleColor": "#88bbff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Stability",
          "Dimensional Anchor"
        ]
      }
    },
    {
      "name": "Temporal Stability",
      "description": "Core particles stabilize temporal fluctuations",
      "rarityTier": "Epic",
      "role": "CORE",
      "statType": "Temporal",
      "bonusAmount": 40,
      "physicsLogic": {
        "forceMultiplier": 1.25,
        "rangeMultiplier": 1.25,
        "speedMultiplier": 1.15,
        "stabilityMultiplier": 1.25
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1.2,
        "particleColor": "#99ccff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Anchor",
          "Reality Nexus"
        ]
      }
    },
    {
      "name": "Dimensional Anchor",
      "description": "Core particles anchor dimensional stability",
      "rarityTier": "Legendary",
      "role": "CORE",
      "statType": "Dimensional",
      "bonusAmount": 45,
      "physicsLogic": {
        "forceMultiplier": 1.3,
        "rangeMultiplier": 1.3,
        "speedMultiplier": 1.2,
        "stabilityMultiplier": 1.3
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1.25,
        "particleColor": "#aaddff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Nexus",
          "Cosmic Heart"
        ]
      }
    },
    {
      "name": "Reality Nexus",
      "description": "Core particles form a nexus of reality",
      "rarityTier": "Legendary",
      "role": "CORE",
      "statType": "Reality",
      "bonusAmount": 50,
      "physicsLogic": {
        "forceMultiplier": 1.35,
        "rangeMultiplier": 1.35,
        "speedMultiplier": 1.25,
        "stabilityMultiplier": 1.35
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1.3,
        "particleColor": "#bbeeff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Heart",
          "Primordial Essence"
        ]
      }
    },
    {
      "name": "Cosmic Heart",
      "description": "Core particles form a cosmic heart",
      "rarityTier": "Mythic",
      "role": "CORE",
      "statType": "Cosmic",
      "bonusAmount": 55,
      "physicsLogic": {
        "forceMultiplier": 1.4,
        "rangeMultiplier": 1.4,
        "speedMultiplier": 1.3,
        "stabilityMultiplier": 1.4
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1.35,
        "particleColor": "#ccffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Primordial Essence"
        ]
      }
    },
    {
      "name": "Primordial Essence",
      "description": "Core particles embody primordial essence",
      "rarityTier": "Mythic",
      "role": "CORE",
      "statType": "Primordial",
      "bonusAmount": 60,
      "physicsLogic": {
        "forceMultiplier": 1.5,
        "rangeMultiplier": 1.5,
        "speedMultiplier": 1.4,
        "stabilityMultiplier": 1.5
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 1.4,
        "particleColor": "#ddffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Heart"
        ]
      }
    }
  ];

export default CORE_CLASS_BONUS_TRAITS;





