// Generated from group_traits/trait_banks/force_calculation/core_force_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { ForceCalculationTrait } from '../../../types/traits/trait';
import { Role, Rarity, ForceType, FalloffType } from '../../../types/core';

export const CORE_FORCE_CALCULATION_TRAITS = [
    {
      "name": "Gravitational Pull",
      "description": "Particles exert a gravitational pull on others",
      "rarityTier": "Common",
      "type": "Attraction",
      "strengthMultiplier": 1.2,
      "rangeMultiplier": 1,
      "falloff": "inverse",
      "physicsLogic": {
        "forceFunction": "inverseSquare",
        "thresholdDistance": 2,
        "maxForce": 5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#3366cc"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Harmonic Attraction",
          "Quantum Binding"
        ]
      }
    },
    {
      "name": "Harmonic Attraction",
      "description": "Particles attract others in harmonic patterns",
      "rarityTier": "Uncommon",
      "type": "Attraction",
      "strengthMultiplier": 1.3,
      "rangeMultiplier": 1.2,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "harmonicOscillator",
        "thresholdDistance": 2.5,
        "maxForce": 6
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#5588dd"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Binding",
          "Resonant Field"
        ]
      }
    },
    {
      "name": "Quantum Binding",
      "description": "Particles bind others through quantum forces",
      "rarityTier": "Rare",
      "type": "Attraction",
      "strengthMultiplier": 1.4,
      "rangeMultiplier": 1.4,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "quantumPotential",
        "thresholdDistance": 3,
        "maxForce": 7
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#6699ee"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Resonant Field",
          "Temporal Anchor"
        ]
      }
    },
    {
      "name": "Resonant Field",
      "description": "Particles create a resonant field of attraction",
      "rarityTier": "Rare",
      "type": "Attraction",
      "strengthMultiplier": 1.5,
      "rangeMultiplier": 1.6,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "resonantField",
        "thresholdDistance": 3.5,
        "maxForce": 8
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#77aaff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Anchor",
          "Dimensional Binding"
        ]
      }
    },
    {
      "name": "Temporal Anchor",
      "description": "Particles anchor others in temporal space",
      "rarityTier": "Epic",
      "type": "Attraction",
      "strengthMultiplier": 1.6,
      "rangeMultiplier": 1.8,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "temporalAnchor",
        "thresholdDistance": 4,
        "maxForce": 9
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#88bbff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Binding",
          "Reality Nexus"
        ]
      }
    },
    {
      "name": "Dimensional Binding",
      "description": "Particles bind others across dimensions",
      "rarityTier": "Epic",
      "type": "Attraction",
      "strengthMultiplier": 1.7,
      "rangeMultiplier": 2,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "dimensionalBinding",
        "thresholdDistance": 4.5,
        "maxForce": 10
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#99ccff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Nexus",
          "Cosmic Attractor"
        ]
      }
    },
    {
      "name": "Reality Nexus",
      "description": "Particles form a nexus that attracts across realities",
      "rarityTier": "Legendary",
      "type": "Attraction",
      "strengthMultiplier": 1.8,
      "rangeMultiplier": 2.2,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "realityNexus",
        "thresholdDistance": 5,
        "maxForce": 11
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#aaddff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Attractor",
          "Universal Binding"
        ]
      }
    },
    {
      "name": "Cosmic Attractor",
      "description": "Particles attract with cosmic-scale forces",
      "rarityTier": "Legendary",
      "type": "Attraction",
      "strengthMultiplier": 1.9,
      "rangeMultiplier": 2.4,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "cosmicAttractor",
        "thresholdDistance": 5.5,
        "maxForce": 12
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#bbeeff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Universal Binding",
          "Primordial Attraction"
        ]
      }
    },
    {
      "name": "Universal Binding",
      "description": "Particles bind with universal forces",
      "rarityTier": "Mythic",
      "type": "Attraction",
      "strengthMultiplier": 2,
      "rangeMultiplier": 2.6,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "universalBinding",
        "thresholdDistance": 6,
        "maxForce": 13
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ccffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Primordial Attraction"
        ]
      }
    },
    {
      "name": "Primordial Attraction",
      "description": "Particles attract with primordial forces of creation",
      "rarityTier": "Mythic",
      "type": "Attraction",
      "strengthMultiplier": 2.1,
      "rangeMultiplier": 2.8,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "primordialAttraction",
        "thresholdDistance": 6.5,
        "maxForce": 14
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ddffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Universal Binding"
        ]
      }
    }
  ];

export default CORE_FORCE_CALCULATION_TRAITS;





