// Generated from group_traits/trait_banks/formation/core_formation_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { FormationTrait } from '../../../types/traits/trait';
import { Role, Rarity, FalloffType } from '../../../types/core';

export const CORE_FORMATION_TRAITS = [
    {
      "name": "Dense Cluster",
      "description": "Particles form a tight spherical cluster",
      "rarityTier": "Common",
      "role": "CORE",
      "pattern": "denseClusterPattern",
      "physicsLogic": {
        "stiffness": 0.7,
        "range": 10,
        "falloff": "quadratic",
        "targetFunction": "sphericalClusterPositions",
        "additionalParameters": {
          "clusterRadius": 5,
          "densityFactor": 1.2
        }
      },
      "visualProperties": {
        "baseColor": "#3366cc",
        "particleScale": 1,
        "trailEffect": false
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cubic Lattice",
          "Tetrahedral Formation"
        ]
      }
    },
    {
      "name": "Cubic Lattice",
      "description": "Particles arrange in a cubic crystal lattice",
      "rarityTier": "Uncommon",
      "role": "CORE",
      "pattern": "cubicLatticePattern",
      "physicsLogic": {
        "stiffness": 0.6,
        "range": 12,
        "falloff": "linear",
        "targetFunction": "cubicLatticePositions",
        "additionalParameters": {
          "latticeSpacing": 2.5,
          "latticeLayers": 3
        }
      },
      "visualProperties": {
        "baseColor": "#5588dd",
        "particleScale": 0.9,
        "trailEffect": false
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Tetrahedral Formation",
          "Spherical Shell"
        ]
      }
    },
    {
      "name": "Tetrahedral Formation",
      "description": "Particles form a tetrahedral structure",
      "rarityTier": "Rare",
      "role": "CORE",
      "pattern": "tetrahedralPattern",
      "physicsLogic": {
        "stiffness": 0.65,
        "range": 15,
        "falloff": "linear",
        "targetFunction": "tetrahedralPositions",
        "additionalParameters": {
          "tetrahedronSize": 8,
          "layerCount": 4
        }
      },
      "visualProperties": {
        "baseColor": "#6699ee",
        "particleScale": 0.85,
        "trailEffect": false
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Spherical Shell",
          "Pulsating Sphere"
        ]
      }
    },
    {
      "name": "Spherical Shell",
      "description": "Particles form a hollow spherical shell",
      "rarityTier": "Rare",
      "role": "CORE",
      "pattern": "sphericalShellPattern",
      "physicsLogic": {
        "stiffness": 0.55,
        "range": 20,
        "falloff": "inverse",
        "targetFunction": "sphericalShellPositions",
        "additionalParameters": {
          "shellRadius": 10,
          "shellThickness": 1
        }
      },
      "visualProperties": {
        "baseColor": "#77aaff",
        "particleScale": 0.8,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Pulsating Sphere",
          "Rotating Cube"
        ]
      }
    },
    {
      "name": "Pulsating Sphere",
      "description": "Particles form a sphere that expands and contracts",
      "rarityTier": "Epic",
      "role": "CORE",
      "pattern": "pulsatingSpherePattern",
      "physicsLogic": {
        "stiffness": 0.5,
        "range": 25,
        "falloff": "exponential",
        "targetFunction": "pulsatingSpherePositions",
        "additionalParameters": {
          "baseRadius": 8,
          "pulsationAmplitude": 4,
          "pulsationFrequency": 0.5
        }
      },
      "visualProperties": {
        "baseColor": "#88bbff",
        "particleScale": 0.75,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Rotating Cube",
          "Helical Core"
        ]
      }
    },
    {
      "name": "Rotating Cube",
      "description": "Particles form a cube that rotates slowly",
      "rarityTier": "Epic",
      "role": "CORE",
      "pattern": "rotatingCubePattern",
      "physicsLogic": {
        "stiffness": 0.6,
        "range": 20,
        "falloff": "linear",
        "targetFunction": "rotatingCubePositions",
        "additionalParameters": {
          "cubeSize": 12,
          "rotationSpeed": 0.2,
          "rotationAxis": [
            0,
            1,
            0
          ]
        }
      },
      "visualProperties": {
        "baseColor": "#99ccff",
        "particleScale": 0.7,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Helical Core",
          "Toroidal Formation"
        ]
      }
    },
    {
      "name": "Helical Core",
      "description": "Particles form a helical structure around a central axis",
      "rarityTier": "Legendary",
      "role": "CORE",
      "pattern": "helicalCorePattern",
      "physicsLogic": {
        "stiffness": 0.45,
        "range": 30,
        "falloff": "exponential",
        "targetFunction": "helicalPositions",
        "additionalParameters": {
          "helixRadius": 6,
          "helixPitch": 1.5,
          "helixTurns": 5
        }
      },
      "visualProperties": {
        "baseColor": "#aaddff",
        "particleScale": 0.65,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Toroidal Formation",
          "Quantum Lattice"
        ]
      }
    },
    {
      "name": "Toroidal Formation",
      "description": "Particles form a torus (donut) shape",
      "rarityTier": "Legendary",
      "role": "CORE",
      "pattern": "toroidalPattern",
      "physicsLogic": {
        "stiffness": 0.4,
        "range": 35,
        "falloff": "inverse",
        "targetFunction": "toroidalPositions",
        "additionalParameters": {
          "torusMajorRadius": 12,
          "torusMinorRadius": 4
        }
      },
      "visualProperties": {
        "baseColor": "#bbeeff",
        "particleScale": 0.6,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Lattice",
          "Fractal Cluster"
        ]
      }
    },
    {
      "name": "Quantum Lattice",
      "description": "Particles arrange in a quantum probability lattice",
      "rarityTier": "Mythic",
      "role": "CORE",
      "pattern": "quantumLatticePattern",
      "physicsLogic": {
        "stiffness": 0.35,
        "range": 40,
        "falloff": "quantum",
        "targetFunction": "quantumLatticePositions",
        "additionalParameters": {
          "quantumStates": 5,
          "superpositionFactor": 0.3,
          "waveFunction": "gaussian"
        }
      },
      "visualProperties": {
        "baseColor": "#ccffff",
        "particleScale": 0.55,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Fractal Cluster"
        ]
      }
    },
    {
      "name": "Fractal Cluster",
      "description": "Particles arrange in a self-similar fractal pattern",
      "rarityTier": "Mythic",
      "role": "CORE",
      "pattern": "fractalClusterPattern",
      "physicsLogic": {
        "stiffness": 0.3,
        "range": 45,
        "falloff": "exponential",
        "targetFunction": "fractalPositions",
        "additionalParameters": {
          "fractalType": "mandelbulb",
          "fractalIterations": 3,
          "fractalScale": 15
        }
      },
      "visualProperties": {
        "baseColor": "#ddffff",
        "particleScale": 0.5,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Lattice"
        ]
      }
    }
  ];

export default CORE_FORMATION_TRAITS;





