// Generated from group_traits/trait_banks/subclass/core_subclass_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { SubclassTrait } from '../../../types/traits/trait';
import { Role, Rarity, AbilityType } from '../../../types/core';

export const CORE_SUBCLASS_TRAITS = [
    {
      "name": "Graviton Core",
      "description": "A core that manipulates gravitational forces",
      "rarityTier": "Common",
      "role": "CORE",
      "formationTrait": "Dense Cluster",
      "abilities": [
        {
          "name": "Gravity Well",
          "description": "Creates a gravity well that pulls nearby particles",
          "type": "Primary",
          "cooldown": 5,
          "physicsLogic": {
            "forceMultiplier": 1.5,
            "rangeMultiplier": 1.2,
            "durationSeconds": 3
          },
          "visualEffects": {
            "particleEffect": "gravity_pulse",
            "areaEffect": "distortion_field",
            "colorFlash": "#3366cc"
          }
        },
        {
          "name": "Mass Shift",
          "description": "Temporarily increases the mass of the core",
          "type": "Secondary",
          "cooldown": 8,
          "physicsLogic": {
            "forceMultiplier": 1.3,
            "rangeMultiplier": 1,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "mass_increase",
            "areaEffect": "none",
            "colorFlash": "#5588dd"
          }
        }
      ],
      "synergy": "Works well with Movement subclasses for enhanced mobility",
      "themeProperties": {
        "primaryColor": "#3366cc",
        "secondaryColor": "#5588dd",
        "particleEffect": "gravitational_ripple",
        "soundEffect": "low_gravity_hum"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Core",
          "Resonance Core"
        ]
      }
    },
    {
      "name": "Resonance Core",
      "description": "A core that resonates with harmonic frequencies",
      "rarityTier": "Uncommon",
      "role": "CORE",
      "formationTrait": "Cubic Lattice",
      "abilities": [
        {
          "name": "Harmonic Wave",
          "description": "Emits a harmonic wave that affects nearby particles",
          "type": "Primary",
          "cooldown": 6,
          "physicsLogic": {
            "forceMultiplier": 1.4,
            "rangeMultiplier": 1.3,
            "durationSeconds": 3
          },
          "visualEffects": {
            "particleEffect": "harmonic_pulse",
            "areaEffect": "wave_ripple",
            "colorFlash": "#6699ee"
          }
        },
        {
          "name": "Frequency Shift",
          "description": "Shifts the resonant frequency to disrupt enemy particles",
          "type": "Secondary",
          "cooldown": 10,
          "physicsLogic": {
            "forceMultiplier": 1.2,
            "rangeMultiplier": 1.5,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "frequency_shift",
            "areaEffect": "dissonance_field",
            "colorFlash": "#77aaff"
          }
        }
      ],
      "synergy": "Works well with Control subclasses for enhanced coordination",
      "themeProperties": {
        "primaryColor": "#6699ee",
        "secondaryColor": "#77aaff",
        "particleEffect": "resonant_glow",
        "soundEffect": "harmonic_chime"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Core",
          "Energy Core"
        ]
      }
    },
    {
      "name": "Energy Core",
      "description": "A core that channels and distributes energy",
      "rarityTier": "Rare",
      "role": "CORE",
      "formationTrait": "Tetrahedral Formation",
      "abilities": [
        {
          "name": "Energy Surge",
          "description": "Releases a surge of energy to empower nearby particles",
          "type": "Primary",
          "cooldown": 8,
          "physicsLogic": {
            "forceMultiplier": 1.6,
            "rangeMultiplier": 1.4,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "energy_burst",
            "areaEffect": "power_field",
            "colorFlash": "#88bbff"
          }
        },
        {
          "name": "Channel Force",
          "description": "Channels energy to create a directed force beam",
          "type": "Secondary",
          "cooldown": 12,
          "physicsLogic": {
            "forceMultiplier": 1.8,
            "rangeMultiplier": 1.6,
            "durationSeconds": 3
          },
          "visualEffects": {
            "particleEffect": "force_beam",
            "areaEffect": "energy_trail",
            "colorFlash": "#99ccff"
          }
        },
        {
          "name": "Energy Nexus",
          "description": "Forms an energy nexus that enhances all nearby particles",
          "type": "Unique",
          "cooldown": 20,
          "physicsLogic": {
            "forceMultiplier": 1.5,
            "rangeMultiplier": 2,
            "durationSeconds": 6
          },
          "visualEffects": {
            "particleEffect": "nexus_formation",
            "areaEffect": "energy_field",
            "colorFlash": "#aaddff"
          }
        }
      ],
      "synergy": "Works well with Attack subclasses for enhanced offensive capabilities",
      "themeProperties": {
        "primaryColor": "#88bbff",
        "secondaryColor": "#aaddff",
        "particleEffect": "energy_flow",
        "soundEffect": "power_surge"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Core",
          "Temporal Core"
        ]
      }
    },
    {
      "name": "Quantum Core",
      "description": "A core that manipulates quantum probabilities",
      "rarityTier": "Epic",
      "role": "CORE",
      "formationTrait": "Pulsating Sphere",
      "abilities": [
        {
          "name": "Quantum Fluctuation",
          "description": "Creates quantum fluctuations that affect particle behavior",
          "type": "Primary",
          "cooldown": 10,
          "physicsLogic": {
            "forceMultiplier": 1.7,
            "rangeMultiplier": 1.5,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "quantum_shift",
            "areaEffect": "probability_field",
            "colorFlash": "#bbeeff"
          }
        },
        {
          "name": "Entanglement",
          "description": "Entangles particles to synchronize their behavior",
          "type": "Secondary",
          "cooldown": 15,
          "physicsLogic": {
            "forceMultiplier": 1.5,
            "rangeMultiplier": 1.8,
            "durationSeconds": 7
          },
          "visualEffects": {
            "particleEffect": "entanglement_beam",
            "areaEffect": "quantum_link",
            "colorFlash": "#ccffff"
          }
        },
        {
          "name": "Superposition",
          "description": "Places particles in a state of superposition for unpredictable behavior",
          "type": "Unique",
          "cooldown": 25,
          "physicsLogic": {
            "forceMultiplier": 1.9,
            "rangeMultiplier": 1.7,
            "durationSeconds": 6
          },
          "visualEffects": {
            "particleEffect": "superposition_blur",
            "areaEffect": "quantum_field",
            "colorFlash": "#ddffff"
          }
        }
      ],
      "synergy": "Works well with all subclasses due to quantum nature",
      "themeProperties": {
        "primaryColor": "#bbeeff",
        "secondaryColor": "#ddffff",
        "particleEffect": "quantum_shimmer",
        "soundEffect": "quantum_fluctuation"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Core",
          "Reality Core"
        ]
      }
    },
    {
      "name": "Temporal Core",
      "description": "A core that manipulates the flow of time",
      "rarityTier": "Legendary",
      "role": "CORE",
      "formationTrait": "Helical Core",
      "abilities": [
        {
          "name": "Time Dilation",
          "description": "Dilates time in a local area, affecting particle speeds",
          "type": "Primary",
          "cooldown": 12,
          "physicsLogic": {
            "forceMultiplier": 1.8,
            "rangeMultiplier": 1.6,
            "durationSeconds": 6
          },
          "visualEffects": {
            "particleEffect": "time_ripple",
            "areaEffect": "temporal_distortion",
            "colorFlash": "#aaddff"
          }
        },
        {
          "name": "Temporal Shift",
          "description": "Shifts particles slightly through time for strategic advantage",
          "type": "Secondary",
          "cooldown": 18,
          "physicsLogic": {
            "forceMultiplier": 1.6,
            "rangeMultiplier": 2,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "time_shift",
            "areaEffect": "echo_trail",
            "colorFlash": "#bbeeff"
          }
        },
        {
          "name": "Chronostasis",
          "description": "Creates a field of frozen time around enemies",
          "type": "Unique",
          "cooldown": 30,
          "physicsLogic": {
            "forceMultiplier": 2,
            "rangeMultiplier": 1.8,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "time_stop",
            "areaEffect": "frozen_moment",
            "colorFlash": "#ccffff"
          }
        },
        {
          "name": "Temporal Nexus",
          "description": "Forms a nexus of temporal energy that affects all nearby particles",
          "type": "CrowdControl",
          "cooldown": 35,
          "physicsLogic": {
            "forceMultiplier": 1.9,
            "rangeMultiplier": 2.2,
            "durationSeconds": 8
          },
          "visualEffects": {
            "particleEffect": "time_vortex",
            "areaEffect": "temporal_field",
            "colorFlash": "#ddffff"
          }
        }
      ],
      "synergy": "Works well with Movement subclasses for temporal mobility",
      "themeProperties": {
        "primaryColor": "#aaddff",
        "secondaryColor": "#ddffff",
        "particleEffect": "time_echo",
        "soundEffect": "clock_reversal"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Core",
          "Cosmic Core"
        ]
      }
    },
    {
      "name": "Reality Core",
      "description": "A core that manipulates the fabric of reality",
      "rarityTier": "Mythic",
      "role": "CORE",
      "formationTrait": "Quantum Lattice",
      "abilities": [
        {
          "name": "Reality Warp",
          "description": "Warps reality in a local area, affecting particle physics",
          "type": "Primary",
          "cooldown": 15,
          "physicsLogic": {
            "forceMultiplier": 2,
            "rangeMultiplier": 1.8,
            "durationSeconds": 7
          },
          "visualEffects": {
            "particleEffect": "reality_distortion",
            "areaEffect": "warped_space",
            "colorFlash": "#bbeeff"
          }
        },
        {
          "name": "Dimensional Fold",
          "description": "Folds dimensions to create shortcuts for friendly particles",
          "type": "Secondary",
          "cooldown": 20,
          "physicsLogic": {
            "forceMultiplier": 1.8,
            "rangeMultiplier": 2.2,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "dimension_fold",
            "areaEffect": "spatial_rift",
            "colorFlash": "#ccffff"
          }
        },
        {
          "name": "Reality Anchor",
          "description": "Anchors reality to prevent enemy manipulation",
          "type": "Unique",
          "cooldown": 35,
          "physicsLogic": {
            "forceMultiplier": 2.2,
            "rangeMultiplier": 2,
            "durationSeconds": 8
          },
          "visualEffects": {
            "particleEffect": "reality_anchor",
            "areaEffect": "stabilization_field",
            "colorFlash": "#ddffff"
          }
        },
        {
          "name": "Existential Manipulation",
          "description": "Manipulates the very existence of particles",
          "type": "CrowdControl",
          "cooldown": 40,
          "physicsLogic": {
            "forceMultiplier": 2.5,
            "rangeMultiplier": 2.5,
            "durationSeconds": 6
          },
          "visualEffects": {
            "particleEffect": "existence_flicker",
            "areaEffect": "reality_bubble",
            "colorFlash": "#eeffff"
          }
        }
      ],
      "synergy": "Works well with Defense subclasses for reality-based protection",
      "themeProperties": {
        "primaryColor": "#bbeeff",
        "secondaryColor": "#eeffff",
        "particleEffect": "reality_shimmer",
        "soundEffect": "reality_shift"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Core"
        ]
      }
    },
    {
      "name": "Cosmic Core",
      "description": "A core that channels cosmic forces of creation",
      "rarityTier": "Mythic",
      "role": "CORE",
      "formationTrait": "Fractal Cluster",
      "abilities": [
        {
          "name": "Cosmic Ray",
          "description": "Emits a powerful cosmic ray that affects all particles in its path",
          "type": "Primary",
          "cooldown": 18,
          "physicsLogic": {
            "forceMultiplier": 2.2,
            "rangeMultiplier": 2,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "cosmic_beam",
            "areaEffect": "stellar_trail",
            "colorFlash": "#ccffff"
          }
        },
        {
          "name": "Stellar Fusion",
          "description": "Creates a miniature star that empowers nearby particles",
          "type": "Secondary",
          "cooldown": 25,
          "physicsLogic": {
            "forceMultiplier": 2,
            "rangeMultiplier": 2.5,
            "durationSeconds": 7
          },
          "visualEffects": {
            "particleEffect": "fusion_glow",
            "areaEffect": "star_formation",
            "colorFlash": "#ddffff"
          }
        },
        {
          "name": "Universal Constant",
          "description": "Alters universal constants in a local area",
          "type": "Unique",
          "cooldown": 40,
          "physicsLogic": {
            "forceMultiplier": 2.5,
            "rangeMultiplier": 2.2,
            "durationSeconds": 8
          },
          "visualEffects": {
            "particleEffect": "constant_shift",
            "areaEffect": "physics_alteration",
            "colorFlash": "#eeffff"
          }
        },
        {
          "name": "Creation Surge",
          "description": "Channels the primordial forces of creation",
          "type": "CrowdControl",
          "cooldown": 50,
          "physicsLogic": {
            "forceMultiplier": 3,
            "rangeMultiplier": 3,
            "durationSeconds": 10
          },
          "visualEffects": {
            "particleEffect": "creation_aura",
            "areaEffect": "genesis_field",
            "colorFlash": "#ffffff"
          }
        }
      ],
      "synergy": "Works well with all subclasses, enhancing their cosmic potential",
      "themeProperties": {
        "primaryColor": "#ccffff",
        "secondaryColor": "#ffffff",
        "particleEffect": "cosmic_glow",
        "soundEffect": "universal_harmony"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Core"
        ]
      }
    }
  ];

export default CORE_SUBCLASS_TRAITS;





