// Generated from group_traits/trait_banks/visual/core_visual_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { VisualTrait } from '../../../types/traits/trait';
import { Role, Rarity } from '../../../types/core';

export const CORE_VISUAL_TRAITS: VisualTrait[] = [
    {
      "id": "core_visual_sphere",
      "name": "Sphere",
      "description": "A spherical visual trait that enhances core abilities.",
      "shape": "Sphere",
      "colorScheme": "Blue Gradient",
      "visualEffect": "Subtle Glow",
      "rarityTier": "Common",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "SphereGeometry",
        "material": "MeshStandardMaterial",
        "scale": 1,
        "emissive": false,
        "opacity": 1,
        "colorHex": "#3366cc"
      },
      "animationProperties": {
        "pulseRate": 0,
        "rotationSpeed": 0,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cube",
          "Pulsating Sphere"
        ]
      }
    },
    {
      "shape": "Cube",
      "colorScheme": "Deep Blue",
      "visualEffect": "Edge Highlight",
      "rarityTier": "Uncommon",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "BoxGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.9,
        "emissive": false,
        "opacity": 1,
        "colorHex": "#5588dd"
      },
      "animationProperties": {
        "pulseRate": 0,
        "rotationSpeed": 0.1,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Tetrahedron",
          "Glowing Cube"
        ]
      }
    },
    {
      "shape": "Tetrahedron",
      "colorScheme": "Azure",
      "visualEffect": "Vertex Glow",
      "rarityTier": "Rare",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "TetrahedronGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.95,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#6699ee"
      },
      "animationProperties": {
        "pulseRate": 0.1,
        "rotationSpeed": 0.2,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Octahedron",
          "Crystalline Tetrahedron"
        ]
      }
    },
    {
      "shape": "Octahedron",
      "colorScheme": "Sapphire",
      "visualEffect": "Face Shimmer",
      "rarityTier": "Rare",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "OctahedronGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.9,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#77aaff"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.3,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dodecahedron",
          "Pulsating Octahedron"
        ]
      }
    },
    {
      "shape": "Dodecahedron",
      "colorScheme": "Cerulean",
      "visualEffect": "Facet Glow",
      "rarityTier": "Epic",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "DodecahedronGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#88bbff"
      },
      "animationProperties": {
        "pulseRate": 0.3,
        "rotationSpeed": 0.4,
        "trailLength": 0.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Icosahedron",
          "Energized Dodecahedron"
        ]
      }
    },
    {
      "shape": "Icosahedron",
      "colorScheme": "Cobalt",
      "visualEffect": "Energy Aura",
      "rarityTier": "Epic",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "IcosahedronGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.05,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#99ccff"
      },
      "animationProperties": {
        "pulseRate": 0.4,
        "rotationSpeed": 0.5,
        "trailLength": 1
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Torus",
          "Quantum Icosahedron"
        ]
      }
    },
    {
      "shape": "Torus",
      "colorScheme": "Celestial Blue",
      "visualEffect": "Energy Flow",
      "rarityTier": "Legendary",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "TorusGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.1,
        "emissive": true,
        "opacity": 0.9,
        "colorHex": "#aaddff"
      },
      "animationProperties": {
        "pulseRate": 0.5,
        "rotationSpeed": 0.6,
        "trailLength": 1.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Toroid Knot",
          "Quantum Torus"
        ]
      }
    },
    {
      "shape": "Toroid Knot",
      "colorScheme": "Ethereal Blue",
      "visualEffect": "Dimensional Shift",
      "rarityTier": "Legendary",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "TorusKnotGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.15,
        "emissive": true,
        "opacity": 0.85,
        "colorHex": "#bbeeff"
      },
      "animationProperties": {
        "pulseRate": 0.6,
        "rotationSpeed": 0.7,
        "trailLength": 2
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Sphere",
          "Fractal Knot"
        ]
      }
    },
    {
      "shape": "Quantum Sphere",
      "colorScheme": "Quantum Blue",
      "visualEffect": "Probability Cloud",
      "rarityTier": "Mythic",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "SphereGeometry",
        "material": "ShaderMaterial",
        "scale": 1.2,
        "emissive": true,
        "opacity": 0.8,
        "colorHex": "#ccffff"
      },
      "animationProperties": {
        "pulseRate": 0.7,
        "rotationSpeed": 0.8,
        "trailLength": 2.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Fractal Sphere",
          "Cosmic Core"
        ]
      }
    },
    {
      "shape": "Fractal Sphere",
      "colorScheme": "Cosmic Blue",
      "visualEffect": "Reality Distortion",
      "rarityTier": "Mythic",
      "role": "CORE",
      "renderingProperties": {
        "geometry": "CustomFractalGeometry",
        "material": "ShaderMaterial",
        "scale": 1.25,
        "emissive": true,
        "opacity": 0.75,
        "colorHex": "#ddffff"
      },
      "animationProperties": {
        "pulseRate": 0.8,
        "rotationSpeed": 0.9,
        "trailLength": 3
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Sphere",
          "Cosmic Core"
        ]
      }
    }
  ];

export default CORE_VISUAL_TRAITS;





