// Generated from group_traits/trait_banks/force_calculation/control_force_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { ForceCalculationTrait } from '../../../types/traits/trait';
import { Role, Rarity, ForceType, FalloffType } from '../../../types/core';

export const CONTROL_FORCE_CALCULATION_TRAITS = [
    {
      "name": "Directive Influence",
      "description": "Particles exert a directive influence on others",
      "rarityTier": "Common",
      "type": "Alignment",
      "strengthMultiplier": 1.2,
      "rangeMultiplier": 1.5,
      "falloff": "linear",
      "physicsLogic": {
        "forceFunction": "directiveAlignment",
        "thresholdDistance": 5,
        "maxForce": 4
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#cc33cc"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Harmonic Control",
          "Neural Influence"
        ]
      }
    },
    {
      "name": "Harmonic Control",
      "description": "Particles control others through harmonic resonance",
      "rarityTier": "Uncommon",
      "type": "Alignment",
      "strengthMultiplier": 1.3,
      "rangeMultiplier": 1.7,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "harmonicControl",
        "thresholdDistance": 5.5,
        "maxForce": 4.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#dd55dd"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Neural Influence",
          "Quantum Control"
        ]
      }
    },
    {
      "name": "Neural Influence",
      "description": "Particles influence others like a neural network",
      "rarityTier": "Rare",
      "type": "Alignment",
      "strengthMultiplier": 1.4,
      "rangeMultiplier": 1.9,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "neuralInfluence",
        "thresholdDistance": 6,
        "maxForce": 5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ee77ee"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Control",
          "Hive Mind Synchronization"
        ]
      }
    },
    {
      "name": "Quantum Control",
      "description": "Particles control others through quantum entanglement",
      "rarityTier": "Rare",
      "type": "Alignment",
      "strengthMultiplier": 1.5,
      "rangeMultiplier": 2.1,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "quantumControl",
        "thresholdDistance": 6.5,
        "maxForce": 5.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ff99ff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Hive Mind Synchronization",
          "Temporal Orchestration"
        ]
      }
    },
    {
      "name": "Hive Mind Synchronization",
      "description": "Particles synchronize others in a hive mind",
      "rarityTier": "Epic",
      "type": "Alignment",
      "strengthMultiplier": 1.6,
      "rangeMultiplier": 2.3,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "hiveMindSync",
        "thresholdDistance": 7,
        "maxForce": 6
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffaaff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Orchestration",
          "Reality Manipulation"
        ]
      }
    },
    {
      "name": "Temporal Orchestration",
      "description": "Particles orchestrate others through temporal manipulation",
      "rarityTier": "Epic",
      "type": "Alignment",
      "strengthMultiplier": 1.7,
      "rangeMultiplier": 2.5,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "temporalOrchestration",
        "thresholdDistance": 7.5,
        "maxForce": 6.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffbbff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Manipulation",
          "Cosmic Orchestration"
        ]
      }
    },
    {
      "name": "Reality Manipulation",
      "description": "Particles manipulate reality to control others",
      "rarityTier": "Legendary",
      "type": "Alignment",
      "strengthMultiplier": 1.8,
      "rangeMultiplier": 2.7,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "realityManipulation",
        "thresholdDistance": 8,
        "maxForce": 7
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffccff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Orchestration",
          "Universal Conductor"
        ]
      }
    },
    {
      "name": "Cosmic Orchestration",
      "description": "Particles orchestrate others with cosmic forces",
      "rarityTier": "Legendary",
      "type": "Alignment",
      "strengthMultiplier": 1.9,
      "rangeMultiplier": 2.9,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "cosmicOrchestration",
        "thresholdDistance": 8.5,
        "maxForce": 7.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffddff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Universal Conductor",
          "Multiversal Harmony"
        ]
      }
    },
    {
      "name": "Universal Conductor",
      "description": "Particles conduct universal forces to control others",
      "rarityTier": "Mythic",
      "type": "Alignment",
      "strengthMultiplier": 2,
      "rangeMultiplier": 3.1,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "universalConductor",
        "thresholdDistance": 9,
        "maxForce": 8
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffeeff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Multiversal Harmony"
        ]
      }
    },
    {
      "name": "Multiversal Harmony",
      "description": "Particles harmonize others across multiple realities",
      "rarityTier": "Mythic",
      "type": "Alignment",
      "strengthMultiplier": 2.1,
      "rangeMultiplier": 3.3,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "multiversalHarmony",
        "thresholdDistance": 9.5,
        "maxForce": 8.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Universal Conductor"
        ]
      }
    }
  ];

export default CONTROL_FORCE_CALCULATION_TRAITS;





