// Generated from group_traits/trait_banks/formation/control_formation_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { FormationTrait } from '../../../types/traits/trait';
import { Role, Rarity, FalloffType } from '../../../types/core';

export const CONTROL_FORMATION_TRAITS = [
    {
      "name": "Orbital Ring",
      "description": "Particles orbit in a ring formation",
      "rarityTier": "Common",
      "role": "CONTROL",
      "pattern": "orbitalRingPattern",
      "physicsLogic": {
        "stiffness": 0.65,
        "range": 15,
        "falloff": "linear",
        "targetFunction": "orbitalRingPositions",
        "additionalParameters": {
          "ringRadius": 12,
          "orbitSpeed": 0.3
        }
      },
      "visualProperties": {
        "baseColor": "#cc33cc",
        "particleScale": 0.9,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dual Rings",
          "Spiral Formation"
        ]
      }
    },
    {
      "name": "Dual Rings",
      "description": "Particles orbit in two perpendicular rings",
      "rarityTier": "Uncommon",
      "role": "CONTROL",
      "pattern": "dualRingsPattern",
      "physicsLogic": {
        "stiffness": 0.6,
        "range": 18,
        "falloff": "linear",
        "targetFunction": "dualRingsPositions",
        "additionalParameters": {
          "ringRadius": 10,
          "orbitSpeed": [
            0.25,
            0.35
          ]
        }
      },
      "visualProperties": {
        "baseColor": "#dd55dd",
        "particleScale": 0.85,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Spiral Formation",
          "Planetary System"
        ]
      }
    },
    {
      "name": "Spiral Formation",
      "description": "Particles arrange in a spiral pattern",
      "rarityTier": "Rare",
      "role": "CONTROL",
      "pattern": "spiralPattern",
      "physicsLogic": {
        "stiffness": 0.55,
        "range": 20,
        "falloff": "quadratic",
        "targetFunction": "spiralPositions",
        "additionalParameters": {
          "spiralRadius": 15,
          "spiralTurns": 3,
          "spiralPitch": 1.2
        }
      },
      "visualProperties": {
        "baseColor": "#ee77ee",
        "particleScale": 0.8,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Planetary System",
          "Vortex Formation"
        ]
      }
    },
    {
      "name": "Planetary System",
      "description": "Particles orbit in a planetary system formation",
      "rarityTier": "Rare",
      "role": "CONTROL",
      "pattern": "planetarySystemPattern",
      "physicsLogic": {
        "stiffness": 0.5,
        "range": 25,
        "falloff": "inverse",
        "targetFunction": "planetarySystemPositions",
        "additionalParameters": {
          "orbits": [
            5,
            8,
            12,
            16,
            20
          ],
          "orbitSpeeds": [
            0.5,
            0.4,
            0.3,
            0.2,
            0.1
          ]
        }
      },
      "visualProperties": {
        "baseColor": "#ff99ff",
        "particleScale": 0.75,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex Formation",
          "Harmonic Oscillator"
        ]
      }
    },
    {
      "name": "Vortex Formation",
      "description": "Particles form a swirling vortex",
      "rarityTier": "Epic",
      "role": "CONTROL",
      "pattern": "vortexPattern",
      "physicsLogic": {
        "stiffness": 0.45,
        "range": 30,
        "falloff": "exponential",
        "targetFunction": "vortexPositions",
        "additionalParameters": {
          "vortexRadius": 12,
          "vortexHeight": 20,
          "swirlingSpeed": 0.4
        }
      },
      "visualProperties": {
        "baseColor": "#ffaaff",
        "particleScale": 0.7,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Harmonic Oscillator",
          "Quantum Controller"
        ]
      }
    },
    {
      "name": "Harmonic Oscillator",
      "description": "Particles oscillate in harmonic patterns",
      "rarityTier": "Epic",
      "role": "CONTROL",
      "pattern": "harmonicOscillatorPattern",
      "physicsLogic": {
        "stiffness": 0.4,
        "range": 35,
        "falloff": "quadratic",
        "targetFunction": "harmonicOscillatorPositions",
        "additionalParameters": {
          "oscillationAmplitude": [
            5,
            3,
            4
          ],
          "oscillationFrequency": [
            0.3,
            0.5,
            0.4
          ],
          "phaseShift": [
            0,
            1.57,
            3.14
          ]
        }
      },
      "visualProperties": {
        "baseColor": "#ffbbff",
        "particleScale": 0.65,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Controller",
          "Temporal Manipulator"
        ]
      }
    },
    {
      "name": "Quantum Controller",
      "description": "Particles exist in quantum superposition states",
      "rarityTier": "Legendary",
      "role": "CONTROL",
      "pattern": "quantumControllerPattern",
      "physicsLogic": {
        "stiffness": 0.35,
        "range": 40,
        "falloff": "quantum",
        "targetFunction": "quantumControllerPositions",
        "additionalParameters": {
          "quantumStates": 4,
          "collapseRate": 0.2,
          "entanglementFactor": 0.7
        }
      },
      "visualProperties": {
        "baseColor": "#ffccff",
        "particleScale": 0.6,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Manipulator",
          "Reality Anchor"
        ]
      }
    },
    {
      "name": "Temporal Manipulator",
      "description": "Particles form patterns that manipulate local time flow",
      "rarityTier": "Legendary",
      "role": "CONTROL",
      "pattern": "temporalManipulatorPattern",
      "physicsLogic": {
        "stiffness": 0.3,
        "range": 45,
        "falloff": "exponential",
        "targetFunction": "temporalManipulatorPositions",
        "additionalParameters": {
          "timeWarpFactor": 0.5,
          "temporalRadius": 15,
          "temporalFrequency": 0.1
        }
      },
      "visualProperties": {
        "baseColor": "#ffddff",
        "particleScale": 0.55,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Anchor",
          "Cosmic Conductor"
        ]
      }
    },
    {
      "name": "Reality Anchor",
      "description": "Particles form a pattern that stabilizes reality",
      "rarityTier": "Mythic",
      "role": "CONTROL",
      "pattern": "realityAnchorPattern",
      "physicsLogic": {
        "stiffness": 0.25,
        "range": 50,
        "falloff": "quantum",
        "targetFunction": "realityAnchorPositions",
        "additionalParameters": {
          "dimensionalLayers": 5,
          "stabilityFactor": 0.8,
          "anchorPoints": 7
        }
      },
      "visualProperties": {
        "baseColor": "#ffeeff",
        "particleScale": 0.5,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Conductor"
        ]
      }
    },
    {
      "name": "Cosmic Conductor",
      "description": "Particles form a pattern that conducts cosmic energy",
      "rarityTier": "Mythic",
      "role": "CONTROL",
      "pattern": "cosmicConductorPattern",
      "physicsLogic": {
        "stiffness": 0.2,
        "range": 55,
        "falloff": "quantum",
        "targetFunction": "cosmicConductorPositions",
        "additionalParameters": {
          "energyChannels": 9,
          "conductionEfficiency": 0.9,
          "resonanceFrequency": 0.05
        }
      },
      "visualProperties": {
        "baseColor": "#ffffff",
        "particleScale": 0.45,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Anchor"
        ]
      }
    }
  ];

export default CONTROL_FORMATION_TRAITS;





