// Generated from group_traits/trait_banks/subclass/control_subclass_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { SubclassTrait } from '../../../types/traits/trait';
import { Role, Rarity, AbilityType } from '../../../types/core';

export const CONTROL_SUBCLASS_TRAITS = [
    {
      "name": "Neural Controller",
      "description": "A controller that functions like a neural network",
      "rarityTier": "Common",
      "role": "CONTROL",
      "formationTrait": "Orbital Ring",
      "abilities": [
        {
          "name": "Neural Link",
          "description": "Creates neural links between particles for coordinated movement",
          "type": "Primary",
          "cooldown": 5,
          "physicsLogic": {
            "forceMultiplier": 1.3,
            "rangeMultiplier": 1.4,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "neural_pulse",
            "areaEffect": "link_network",
            "colorFlash": "#cc33cc"
          }
        },
        {
          "name": "Synaptic Boost",
          "description": "Boosts the response time of linked particles",
          "type": "Secondary",
          "cooldown": 8,
          "physicsLogic": {
            "forceMultiplier": 1.2,
            "rangeMultiplier": 1.3,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "synapse_flash",
            "areaEffect": "none",
            "colorFlash": "#dd55dd"
          }
        }
      ],
      "synergy": "Works well with Core subclasses for enhanced stability",
      "themeProperties": {
        "primaryColor": "#cc33cc",
        "secondaryColor": "#dd55dd",
        "particleEffect": "neural_glow",
        "soundEffect": "synapse_firing"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Harmonic Controller",
          "Quantum Director"
        ]
      }
    },
    {
      "name": "Harmonic Controller",
      "description": "A controller that uses harmonic resonance for control",
      "rarityTier": "Uncommon",
      "role": "CONTROL",
      "formationTrait": "Dual Rings",
      "abilities": [
        {
          "name": "Resonance Field",
          "description": "Creates a field of harmonic resonance for enhanced control",
          "type": "Primary",
          "cooldown": 6,
          "physicsLogic": {
            "forceMultiplier": 1.4,
            "rangeMultiplier": 1.5,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "harmonic_wave",
            "areaEffect": "resonance_field",
            "colorFlash": "#ee77ee"
          }
        },
        {
          "name": "Frequency Control",
          "description": "Adjusts frequencies to control particle behavior",
          "type": "Secondary",
          "cooldown": 10,
          "physicsLogic": {
            "forceMultiplier": 1.3,
            "rangeMultiplier": 1.6,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "frequency_shift",
            "areaEffect": "harmonic_grid",
            "colorFlash": "#ff99ff"
          }
        }
      ],
      "synergy": "Works well with Movement subclasses for coordinated mobility",
      "themeProperties": {
        "primaryColor": "#ee77ee",
        "secondaryColor": "#ff99ff",
        "particleEffect": "harmonic_pulse",
        "soundEffect": "resonant_tone"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Director",
          "Hive Mind"
        ]
      }
    },
    {
      "name": "Quantum Director",
      "description": "A controller that uses quantum entanglement for control",
      "rarityTier": "Rare",
      "role": "CONTROL",
      "formationTrait": "Spiral Formation",
      "abilities": [
        {
          "name": "Quantum Entanglement",
          "description": "Entangles particles for instantaneous coordination",
          "type": "Primary",
          "cooldown": 8,
          "physicsLogic": {
            "forceMultiplier": 1.5,
            "rangeMultiplier": 1.7,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "entanglement_beam",
            "areaEffect": "quantum_network",
            "colorFlash": "#ffaaff"
          }
        },
        {
          "name": "Probability Shift",
          "description": "Shifts quantum probabilities to favor desired outcomes",
          "type": "Secondary",
          "cooldown": 12,
          "physicsLogic": {
            "forceMultiplier": 1.4,
            "rangeMultiplier": 1.8,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "probability_wave",
            "areaEffect": "quantum_field",
            "colorFlash": "#ffbbff"
          }
        }
      ],
      "synergy": "Works well with Defense subclasses for quantum shielding",
      "themeProperties": {
        "primaryColor": "#ffaaff",
        "secondaryColor": "#ffbbff",
        "particleEffect": "quantum_shimmer",
        "soundEffect": "quantum_fluctuation"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Hive Mind",
          "Temporal Conductor"
        ]
      }
    }
  ];

export default CONTROL_SUBCLASS_TRAITS;





