// Generated from group_traits/trait_banks/visual/control_visual_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { VisualTrait } from '../../../types/traits/trait';
import { Role, Rarity } from '../../../types/core';

export const CONTROL_VISUAL_TRAITS: VisualTrait[] = [
    {
      "id": "control_visual_ring",
      "name": "Ring",
      "description": "A circular ring-shaped visual trait that enhances control abilities.",
      "shape": "Ring",
      "colorScheme": "Purple Gradient",
      "visualEffect": "Subtle Pulse",
      "rarityTier": Rarity.COMMON,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "TorusGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.9,
        "emissive": false,
        "opacity": 1,
        "colorHex": "#cc33cc"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.3,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dual Ring",
          "Pulsating Ring"
        ]
      }
    },
    {
      "id": "control_visual_dual_ring",
      "name": "Dual Ring",
      "description": "A dual ring structure that pulses with magenta energy",
      "shape": "Dual Ring",
      "colorScheme": "Magenta",
      "visualEffect": "Orbital Glow",
      "rarityTier": Rarity.UNCOMMON,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomDualRingGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.95,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#dd55dd"
      },
      "animationProperties": {
        "pulseRate": 0.3,
        "rotationSpeed": 0.4,
        "trailLength": 0
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Spiral",
          "Resonant Rings"
        ]
      }
    },
    {
      "id": "control_visual_spiral",
      "name": "Spiral",
      "description": "A spiral structure that flows with fuchsia energy",
      "shape": "Spiral",
      "colorScheme": "Fuchsia",
      "visualEffect": "Energy Flow",
      "rarityTier": Rarity.RARE,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomSpiralGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#ee77ee"
      },
      "animationProperties": {
        "pulseRate": 0.4,
        "rotationSpeed": 0.5,
        "trailLength": 0.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Orbital System",
          "Flowing Spiral"
        ]
      }
    },
    {
      "id": "control_visual_orbital_system",
      "name": "Orbital System",
      "description": "An orbital system that glows with orchid energy",
      "shape": "Orbital System",
      "colorScheme": "Orchid",
      "visualEffect": "Planetary Glow",
      "rarityTier": Rarity.RARE,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomOrbitalGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.05,
        "emissive": true,
        "opacity": 0.95,
        "colorHex": "#ff99ff"
      },
      "animationProperties": {
        "pulseRate": 0.3,
        "rotationSpeed": 0.6,
        "trailLength": 1
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex",
          "Harmonic System"
        ]
      }
    },
    {
      "id": "control_visual_vortex",
      "name": "Vortex",
      "description": "A vortex structure that swirls with lavender energy",
      "shape": "Vortex",
      "colorScheme": "Lavender",
      "visualEffect": "Swirling Energy",
      "rarityTier": Rarity.EPIC,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomVortexGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.1,
        "emissive": true,
        "opacity": 0.9,
        "colorHex": "#ffaaff"
      },
      "animationProperties": {
        "pulseRate": 0.5,
        "rotationSpeed": 0.7,
        "trailLength": 1.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Harmonic Oscillator",
          "Quantum Controller"
        ]
      }
    },
    {
      "id": "control_visual_harmonic_oscillator",
      "name": "Harmonic Oscillator",
      "description": "A harmonic oscillator that waves with amethyst energy",
      "shape": "Harmonic Oscillator",
      "colorScheme": "Amethyst",
      "visualEffect": "Frequency Waves",
      "rarityTier": Rarity.EPIC,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomOscillatorGeometry",
        "material": "ShaderMaterial",
        "scale": 1.15,
        "emissive": true,
        "opacity": 0.85,
        "colorHex": "#ffbbff"
      },
      "animationProperties": {
        "pulseRate": 0.6,
        "rotationSpeed": 0.5,
        "trailLength": 2
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Controller",
          "Temporal Conductor"
        ]
      }
    },
    {
      "id": "control_visual_quantum_controller",
      "name": "Quantum Controller",
      "description": "A quantum controller that shifts with quantum purple energy",
      "shape": "Quantum Controller",
      "colorScheme": "Quantum Purple",
      "visualEffect": "Probability Shift",
      "rarityTier": Rarity.LEGENDARY,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomQuantumGeometry",
        "material": "ShaderMaterial",
        "scale": 1.2,
        "emissive": true,
        "opacity": 0.8,
        "colorHex": "#ffccff"
      },
      "animationProperties": {
        "pulseRate": 0.7,
        "rotationSpeed": 0.6,
        "trailLength": 2.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Conductor",
          "Reality Weaver"
        ]
      }
    },
    {
      "id": "control_visual_temporal_conductor",
      "name": "Temporal Conductor",
      "description": "A temporal conductor that distorts with chrono purple energy",
      "shape": "Temporal Conductor",
      "colorScheme": "Chrono Purple",
      "visualEffect": "Time Distortion",
      "rarityTier": Rarity.LEGENDARY,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomTemporalGeometry",
        "material": "ShaderMaterial",
        "scale": 1.25,
        "emissive": true,
        "opacity": 0.75,
        "colorHex": "#ffddff"
      },
      "animationProperties": {
        "pulseRate": 0.8,
        "rotationSpeed": 0.4,
        "trailLength": 3
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Weaver",
          "Cosmic Conductor"
        ]
      }
    },
    {
      "id": "control_visual_reality_weaver",
      "name": "Reality Weaver",
      "description": "A reality weaver that fabricates with ethereal purple energy",
      "shape": "Reality Weaver",
      "colorScheme": "Ethereal Purple",
      "visualEffect": "Reality Fabric",
      "rarityTier": Rarity.MYTHIC,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomRealityGeometry",
        "material": "ShaderMaterial",
        "scale": 1.3,
        "emissive": true,
        "opacity": 0.7,
        "colorHex": "#ffeeff"
      },
      "animationProperties": {
        "pulseRate": 0.9,
        "rotationSpeed": 0.3,
        "trailLength": 3.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Conductor",
          "Universal Nexus"
        ]
      }
    },
    {
      "id": "control_visual_universal_nexus",
      "name": "Universal Nexus",
      "description": "A universal nexus that connects with cosmic purple energy",
      "shape": "Universal Nexus",
      "colorScheme": "Cosmic Purple",
      "visualEffect": "Dimensional Nexus",
      "rarityTier": Rarity.MYTHIC,
      "role": Role.CONTROL,
      "renderingProperties": {
        "geometry": "CustomNexusGeometry",
        "material": "ShaderMaterial",
        "scale": 1.35,
        "emissive": true,
        "opacity": 0.65,
        "colorHex": "#ffffff"
      },
      "animationProperties": {
        "pulseRate": 1,
        "rotationSpeed": 0.2,
        "trailLength": 4
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Conductor",
          "Reality Weaver"
        ]
      }
    }
  ];

export default CONTROL_VISUAL_TRAITS;





