// Generated from group_traits/trait_banks/formation/attack_formation_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { FormationTrait } from '../../../types/traits/trait';
import { Role, Rarity, FalloffType } from '../../../types/core';

export const ATTACK_FORMATION_TRAITS: FormationTrait[] = [
    {
      "id": "attack_formation_arrow",
      "name": "Arrow Formation",
      "description": "Particles form an arrow-like formation",
      "rarityTier": Rarity.COMMON,
      "role": Role.ATTACK,
      "pattern": "arrowFormationPattern",
      "physicsLogic": {
        "stiffness": 0.7,
        "range": 12,
        "falloff": FalloffType.LINEAR,
        "targetFunction": "arrowFormationPositions",
        "additionalParameters": {
          "arrowLength": 15,
          "arrowWidth": 8,
          "arrowDirection": [
            0,
            0,
            1
          ]
        }
      },
      "visualProperties": {
        "baseColor": "#ff3333",
        "particleScale": 0.9,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Spear Formation",
          "Pincer Attack"
        ]
      }
    },
    {
      "id": "attack_formation_spear",
      "name": "Spear Formation",
      "description": "Particles form a spear-like formation",
      "rarityTier": Rarity.UNCOMMON,
      "role": Role.ATTACK,
      "pattern": "spearFormationPattern",
      "physicsLogic": {
        "stiffness": 0.65,
        "range": 15,
        "falloff": FalloffType.LINEAR,
        "targetFunction": "spearFormationPositions",
        "additionalParameters": {
          "spearLength": 20,
          "spearWidth": 5,
          "spearRotation": 0.2
        }
      },
      "visualProperties": {
        "baseColor": "#ff5555",
        "particleScale": 0.85,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Pincer Attack",
          "Swarm Assault"
        ]
      }
    },
    {
      "id": "attack_formation_pincer",
      "name": "Pincer Attack",
      "description": "Particles form a pincer-like formation",
      "rarityTier": Rarity.RARE,
      "role": Role.ATTACK,
      "pattern": "pincerAttackPattern",
      "physicsLogic": {
        "stiffness": 0.6,
        "range": 18,
        "falloff": FalloffType.QUADRATIC,
        "targetFunction": "pincerAttackPositions",
        "additionalParameters": {
          "pincerSpan": 16,
          "pincerDepth": 12,
          "closingSpeed": 0.3
        }
      },
      "visualProperties": {
        "baseColor": "#ff7777",
        "particleScale": 0.8,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Swarm Assault",
          "Orbital Strike"
        ]
      }
    },
    {
      "id": "attack_formation_swarm",
      "name": "Swarm Assault",
      "description": "Particles form a swarming attack pattern",
      "rarityTier": Rarity.RARE,
      "role": Role.ATTACK,
      "pattern": "swarmAssaultPattern",
      "physicsLogic": {
        "stiffness": 0.55,
        "range": 20,
        "falloff": FalloffType.INVERSE,
        "targetFunction": "swarmAssaultPositions",
        "additionalParameters": {
          "swarmRadius": 10,
          "swarmDensity": 0.7,
          "swarmSpeed": 0.5
        }
      },
      "visualProperties": {
        "baseColor": "#ff9999",
        "particleScale": 0.75,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Orbital Strike",
          "Blade Vortex"
        ]
      }
    },
    {
      "id": "attack_formation_orbital",
      "name": "Orbital Strike",
      "description": "Particles orbit and strike from multiple angles",
      "rarityTier": Rarity.EPIC,
      "role": Role.ATTACK,
      "pattern": "orbitalStrikePattern",
      "physicsLogic": {
        "stiffness": 0.5,
        "range": 25,
        "falloff": FalloffType.EXPONENTIAL,
        "targetFunction": "orbitalStrikePositions",
        "additionalParameters": {
          "orbitRadius": 15,
          "strikeSpeed": 0.8,
          "strikeAngle": 45
        }
      },
      "visualProperties": {
        "baseColor": "#ffaaaa",
        "particleScale": 0.7,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Blade Vortex",
          "Nova Burst"
        ]
      }
    },
    {
      "id": "attack_formation_blade_vortex",
      "name": "Blade Vortex",
      "description": "Particles form a spinning blade-like vortex",
      "rarityTier": Rarity.EPIC,
      "role": Role.ATTACK,
      "pattern": "bladeVortexPattern",
      "physicsLogic": {
        "stiffness": 0.45,
        "range": 30,
        "falloff": FalloffType.QUADRATIC,
        "targetFunction": "bladeVortexPositions",
        "additionalParameters": {
          "bladeRadius": 12,
          "bladeCount": 5,
          "rotationSpeed": 0.6
        }
      },
      "visualProperties": {
        "baseColor": "#ffbbbb",
        "particleScale": 0.65,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Nova Burst",
          "Phantom Blades"
        ]
      }
    },
    {
      "id": "attack_formation_nova",
      "name": "Nova Burst",
      "description": "Particles form an explosive nova pattern",
      "rarityTier": Rarity.LEGENDARY,
      "role": Role.ATTACK,
      "pattern": "novaBurstPattern",
      "physicsLogic": {
        "stiffness": 0.4,
        "range": 35,
        "falloff": FalloffType.EXPONENTIAL,
        "targetFunction": "novaBurstPositions",
        "additionalParameters": {
          "novaRadius": 18,
          "expansionRate": 0.7,
          "pulseFrequency": 0.3
        }
      },
      "visualProperties": {
        "baseColor": "#ffcccc",
        "particleScale": 0.6,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Phantom Blades",
          "Singularity Cannon"
        ]
      }
    },
    {
      "id": "attack_formation_phantom",
      "name": "Phantom Blades",
      "description": "Particles form ethereal blade formations that phase in and out",
      "rarityTier": Rarity.LEGENDARY,
      "role": Role.ATTACK,
      "pattern": "phantomBladesPattern",
      "physicsLogic": {
        "stiffness": 0.35,
        "range": 40,
        "falloff": FalloffType.QUANTUM,
        "targetFunction": "phantomBladesPositions",
        "additionalParameters": {
          "bladeLength": 25,
          "phaseFrequency": 0.4,
          "bladeCount": 7
        }
      },
      "visualProperties": {
        "baseColor": "#ffdddd",
        "particleScale": 0.55,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Singularity Cannon",
          "Reality Shredder"
        ]
      }
    },
    {
      "id": "attack_formation_singularity",
      "name": "Singularity Cannon",
      "description": "Particles form a cannon that fires concentrated singularities",
      "rarityTier": Rarity.MYTHIC,
      "role": Role.ATTACK,
      "pattern": "singularityCannonPattern",
      "physicsLogic": {
        "stiffness": 0.3,
        "range": 45,
        "falloff": FalloffType.QUANTUM,
        "targetFunction": "singularityCannonPositions",
        "additionalParameters": {
          "cannonLength": 30,
          "cannonDiameter": 8,
          "firingRate": 0.2
        }
      },
      "visualProperties": {
        "baseColor": "#ffeeee",
        "particleScale": 0.5,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Shredder"
        ]
      }
    },
    {
      "id": "attack_formation_reality",
      "name": "Reality Shredder",
      "description": "Particles form a pattern that tears at the fabric of reality",
      "rarityTier": Rarity.MYTHIC,
      "role": Role.ATTACK,
      "pattern": "realityShredderPattern",
      "physicsLogic": {
        "stiffness": 0.25,
        "range": 50,
        "falloff": FalloffType.QUANTUM,
        "targetFunction": "realityShredderPositions",
        "additionalParameters": {
          "shredderWidth": 20,
          "dimensionalTears": 5,
          "tearPropagation": 0.8
        }
      },
      "visualProperties": {
        "baseColor": "#ffffff",
        "particleScale": 0.45,
        "trailEffect": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Singularity Cannon"
        ]
      }
    }
  ];

export default ATTACK_FORMATION_TRAITS;





