// Generated from group_traits/trait_banks/visual/attack_visual_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { VisualTrait } from '../../../types/traits/trait';
import { Rarity, Role } from '../../../types/core';

export const ATTACK_VISUAL_TRAITS: VisualTrait[] = [
    {
      "id": "attack_visual_arrow",
      "name": "Arrow",
      "description": "A sharp, arrow-shaped visual trait that enhances piercing attacks.",
      "shape": "Arrow",
      "colorScheme": "Red Gradient",
      "visualEffect": "Sharp Edge",
      "rarityTier": Rarity.COMMON,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "ConeGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.9,
        "emissive": false,
        "opacity": 1,
        "colorHex": "#ff3333"
      },
      "animationProperties": {
        "pulseRate": 0,
        "rotationSpeed": 0.2,
        "trailLength": 0.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Spear",
          "Glowing Arrow"
        ]
      }
    },
    {
      "id": "attack_visual_spear",
      "name": "Spear",
      "description": "A crimson spear-shaped visual trait with a piercing glow effect.",
      "shape": "Spear",
      "colorScheme": "Crimson",
      "visualEffect": "Piercing Glow",
      "rarityTier": Rarity.UNCOMMON,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomSpearGeometry",
        "material": "MeshStandardMaterial",
        "scale": 1,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#ff5555"
      },
      "animationProperties": {
        "pulseRate": 0.1,
        "rotationSpeed": 0.3,
        "trailLength": 1
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Blade",
          "Energy Spear"
        ]
      }
    },
    {
      "id": "attack_visual_blade",
      "name": "Blade",
      "description": "A sharp, blade-shaped visual trait that enhances cutting attacks.",
      "shape": "Blade",
      "colorScheme": "Scarlet",
      "visualEffect": "Cutting Edge",
      "rarityTier": Rarity.RARE,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomBladeGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.95,
        "emissive": true,
        "opacity": 1,
        "colorHex": "#ff7777"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.4,
        "trailLength": 1.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Shard",
          "Energy Blade"
        ]
      }
    },
    {
      "id": "attack_visual_shard",
      "name": "Shard",
      "description": "A crystalline shard-shaped visual trait that enhances fragmentation attacks.",
      "shape": "Shard",
      "colorScheme": "Ruby",
      "visualEffect": "Fragmentation",
      "rarityTier": Rarity.RARE,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomShardGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.85,
        "emissive": true,
        "opacity": 0.95,
        "colorHex": "#ff9999"
      },
      "animationProperties": {
        "pulseRate": 0.3,
        "rotationSpeed": 0.5,
        "trailLength": 1.2
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Nova",
          "Crystal Shard"
        ]
      }
    },
    {
      "id": "attack_visual_nova",
      "name": "Nova",
      "description": "A radiant nova-shaped visual trait that enhances explosive attacks.",
      "shape": "Nova",
      "colorScheme": "Fiery Red",
      "visualEffect": "Explosive Burst",
      "rarityTier": Rarity.EPIC,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomNovaGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 1.1,
        "emissive": true,
        "opacity": 0.9,
        "colorHex": "#ffaaaa"
      },
      "animationProperties": {
        "pulseRate": 0.5,
        "rotationSpeed": 0.6,
        "trailLength": 2
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex Blade",
          "Quantum Spike"
        ]
      }
    },
    {
      "id": "attack_visual_vortex_blade",
      "name": "Vortex Blade",
      "description": "A spinning vortex blade-shaped visual trait that enhances whirling attacks.",
      "shape": "Vortex Blade",
      "colorScheme": "Inferno",
      "visualEffect": "Spinning Edge",
      "rarityTier": Rarity.EPIC,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomVortexBladeGeometry",
        "material": "ShaderMaterial",
        "scale": 1.05,
        "emissive": true,
        "opacity": 0.85,
        "colorHex": "#ffbbbb"
      },
      "animationProperties": {
        "pulseRate": 0.4,
        "rotationSpeed": 0.8,
        "trailLength": 2.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Spike",
          "Phantom Blade"
        ]
      }
    },
    {
      "id": "attack_visual_quantum_spike",
      "name": "Quantum Spike",
      "description": "A phase-shifting quantum spike-shaped visual trait that enhances penetrating attacks.",
      "shape": "Quantum Spike",
      "colorScheme": "Quantum Red",
      "visualEffect": "Phase Shift",
      "rarityTier": Rarity.LEGENDARY,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomQuantumSpikeGeometry",
        "material": "ShaderMaterial",
        "scale": 1,
        "emissive": true,
        "opacity": 0.8,
        "colorHex": "#ffcccc"
      },
      "animationProperties": {
        "pulseRate": 0.6,
        "rotationSpeed": 0.7,
        "trailLength": 3
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Phantom Blade",
          "Reality Shredder"
        ]
      }
    },
    {
      "id": "attack_visual_phantom_blade",
      "name": "Phantom Blade",
      "description": "An ethereal phantom blade-shaped visual trait that enhances phasing attacks.",
      "shape": "Phantom Blade",
      "colorScheme": "Ethereal Red",
      "visualEffect": "Phasing Edge",
      "rarityTier": Rarity.LEGENDARY,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomPhantomGeometry",
        "material": "ShaderMaterial",
        "scale": 1.15,
        "emissive": true,
        "opacity": 0.7,
        "colorHex": "#ffdddd"
      },
      "animationProperties": {
        "pulseRate": 0.7,
        "rotationSpeed": 0.9,
        "trailLength": 3.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Shredder",
          "Void Rend"
        ]
      }
    },
    {
      "id": "attack_visual_reality_shredder",
      "name": "Reality Shredder",
      "description": "A reality-tearing shredder-shaped visual trait that enhances dimensional attacks.",
      "shape": "Reality Shredder",
      "colorScheme": "Dimensional Red",
      "visualEffect": "Reality Tear",
      "rarityTier": Rarity.MYTHIC,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomShredderGeometry",
        "material": "ShaderMaterial",
        "scale": 1.2,
        "emissive": true,
        "opacity": 0.65,
        "colorHex": "#ffeeee"
      },
      "animationProperties": {
        "pulseRate": 0.8,
        "rotationSpeed": 1,
        "trailLength": 4
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Void Rend",
          "Cosmic Annihilator"
        ]
      }
    },
    {
      "id": "attack_visual_void_rend",
      "name": "Void Rend",
      "description": "A void-tearing rend-shaped visual trait that enhances existential attacks.",
      "shape": "Void Rend",
      "colorScheme": "Cosmic Red",
      "visualEffect": "Existential Tear",
      "rarityTier": Rarity.MYTHIC,
      "role": Role.ATTACK,
      "renderingProperties": {
        "geometry": "CustomVoidGeometry",
        "material": "ShaderMaterial",
        "scale": 1.25,
        "emissive": true,
        "opacity": 0.6,
        "colorHex": "#ffffff"
      },
      "animationProperties": {
        "pulseRate": 0.9,
        "rotationSpeed": 1.1,
        "trailLength": 4.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Annihilator",
          "Reality Shredder"
        ]
      }
    }
  ];

export default ATTACK_VISUAL_TRAITS;





