// Generated from group_traits/trait_banks/behavior/movement_behavior_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { BehaviorTrait } from '../../../types/traits/trait';
import { Role, Rarity, BehaviorType } from '../../../types/core';

export const MOVEMENT_BEHAVIOR_TRAITS = [
    {
      "name": "Swift Current",
      "description": "Particles move in swift, flowing currents",
      "rarityTier": "Common",
      "role": "MOVEMENT",
      "type": "Flowing",
      "physicsLogic": {
        "strength": 0.7,
        "range": 15,
        "priority": 0.8,
        "persistence": 0.8,
        "frequency": 0.4,
        "additionalParameters": {
          "flowSpeed": 0.9,
          "streamlining": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "flow_streak",
        "trailEffect": "current_trail",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Agile Maneuvering",
          "Wave Propulsion"
        ]
      }
    },
    {
      "name": "Agile Maneuvering",
      "description": "Particles maneuver with exceptional agility",
      "rarityTier": "Uncommon",
      "role": "MOVEMENT",
      "type": "Flowing",
      "physicsLogic": {
        "strength": 0.75,
        "range": 12,
        "priority": 0.85,
        "persistence": 0.75,
        "frequency": 0.5,
        "additionalParameters": {
          "turnRate": 0.9,
          "accelerationFactor": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "agility_blur",
        "trailEffect": "maneuver_trail",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Wave Propulsion",
          "Vortex Momentum"
        ]
      }
    },
    {
      "name": "Wave Propulsion",
      "description": "Particles propel using wave-like movements",
      "rarityTier": "Rare",
      "role": "MOVEMENT",
      "type": "Oscillation",
      "physicsLogic": {
        "strength": 0.8,
        "range": 18,
        "priority": 0.9,
        "persistence": 0.8,
        "frequency": 0.6,
        "additionalParameters": {
          "waveAmplitude": 5,
          "waveFrequency": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "wave_ripple",
        "trailEffect": "oscillation_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex Momentum",
          "Quantum Displacement"
        ]
      }
    },
    {
      "name": "Vortex Momentum",
      "description": "Particles generate momentum through vortex formation",
      "rarityTier": "Rare",
      "role": "MOVEMENT",
      "type": "Rotation",
      "physicsLogic": {
        "strength": 0.85,
        "range": 20,
        "priority": 0.95,
        "persistence": 0.85,
        "frequency": 0.4,
        "additionalParameters": {
          "vortexStrength": 0.9,
          "rotationalVelocity": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "vortex_spiral",
        "trailEffect": "spiral_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Displacement",
          "Slipstream Acceleration"
        ]
      }
    },
    {
      "name": "Quantum Displacement",
      "description": "Particles move through quantum displacement",
      "rarityTier": "Epic",
      "role": "MOVEMENT",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 0.9,
        "range": 25,
        "priority": 1,
        "persistence": 0.9,
        "frequency": 0.3,
        "additionalParameters": {
          "displacementDistance": 10,
          "quantumProbability": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "quantum_blur",
        "trailEffect": "probability_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Slipstream Acceleration",
          "Temporal Phasing"
        ]
      }
    },
    {
      "name": "Slipstream Acceleration",
      "description": "Particles create and accelerate through slipstreams",
      "rarityTier": "Epic",
      "role": "MOVEMENT",
      "type": "Flowing",
      "physicsLogic": {
        "strength": 0.95,
        "range": 30,
        "priority": 1,
        "persistence": 0.95,
        "frequency": 0.25,
        "additionalParameters": {
          "slipstreamEfficiency": 0.9,
          "accelerationCurve": 1.5
        }
      },
      "visualEffects": {
        "particleEffect": "slipstream_blur",
        "trailEffect": "acceleration_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Phasing",
          "Dimensional Slipstream"
        ]
      }
    },
    {
      "name": "Temporal Phasing",
      "description": "Particles phase through time for movement",
      "rarityTier": "Legendary",
      "role": "MOVEMENT",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1,
        "range": 35,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.2,
        "additionalParameters": {
          "temporalShift": 0.5,
          "phaseFrequency": 0.3
        }
      },
      "visualEffects": {
        "particleEffect": "temporal_echo",
        "trailEffect": "time_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Slipstream",
          "Cosmic Velocity"
        ]
      }
    },
    {
      "name": "Dimensional Slipstream",
      "description": "Particles travel through dimensional slipstreams",
      "rarityTier": "Legendary",
      "role": "MOVEMENT",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.05,
        "range": 40,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.15,
        "additionalParameters": {
          "dimensionalFold": 0.9,
          "slipstreamStability": 0.8
        }
      },
      "visualEffects": {
        "particleEffect": "dimensional_tear",
        "trailEffect": "reality_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity",
          "Reality Surfing"
        ]
      }
    },
    {
      "name": "Cosmic Velocity",
      "description": "Particles move at cosmic velocities",
      "rarityTier": "Mythic",
      "role": "MOVEMENT",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.1,
        "range": 45,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.1,
        "additionalParameters": {
          "cosmicSpeed": 2,
          "relativisticEffects": 0.9
        }
      },
      "visualEffects": {
        "particleEffect": "cosmic_blur",
        "trailEffect": "light_streak",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Surfing"
        ]
      }
    },
    {
      "name": "Reality Surfing",
      "description": "Particles surf between realities for movement",
      "rarityTier": "Mythic",
      "role": "MOVEMENT",
      "type": "Quantum Fluctuation",
      "physicsLogic": {
        "strength": 1.2,
        "range": 50,
        "priority": 1,
        "persistence": 1,
        "frequency": 0.05,
        "additionalParameters": {
          "realityTransitionRate": 0.9,
          "multiversalNavigation": 1
        }
      },
      "visualEffects": {
        "particleEffect": "reality_shift",
        "trailEffect": "multiverse_wake",
        "colorModulation": true
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity"
        ]
      }
    }
  ];

export default MOVEMENT_BEHAVIOR_TRAITS;





