// Generated from group_traits/trait_banks/class_bonus/movement_class_bonus_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { ClassBonusTrait } from '../../../types/traits/trait';
import { Role, Rarity } from '../../../types/core';

export const MOVEMENT_CLASS_BONUS_TRAITS = [
    {
      "name": "Swift Motion",
      "description": "Increases speed of movement particles",
      "rarityTier": "Common",
      "role": "MOVEMENT",
      "statType": "Speed",
      "bonusAmount": 15,
      "physicsLogic": {
        "forceMultiplier": 1,
        "rangeMultiplier": 1,
        "speedMultiplier": 1.15,
        "stabilityMultiplier": 1
      },
      "visualEffects": {
        "particleGlow": false,
        "particleSize": 0.9,
        "particleColor": "#3399ff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Aerodynamic Form",
          "Momentum Conservation"
        ]
      }
    },
    {
      "name": "Aerodynamic Form",
      "description": "Increases aerodynamics of movement particles",
      "rarityTier": "Uncommon",
      "role": "MOVEMENT",
      "statType": "Aerodynamic",
      "bonusAmount": 20,
      "physicsLogic": {
        "forceMultiplier": 1.05,
        "rangeMultiplier": 1,
        "speedMultiplier": 1.2,
        "stabilityMultiplier": 1
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.85,
        "particleColor": "#55aaff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Momentum Conservation",
          "Slipstream Generation"
        ]
      }
    },
    {
      "name": "Momentum Conservation",
      "description": "Movement particles conserve momentum efficiently",
      "rarityTier": "Rare",
      "role": "MOVEMENT",
      "statType": "Momentum",
      "bonusAmount": 25,
      "physicsLogic": {
        "forceMultiplier": 1.1,
        "rangeMultiplier": 1.05,
        "speedMultiplier": 1.25,
        "stabilityMultiplier": 1.05
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.8,
        "particleColor": "#77bbff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Slipstream Generation",
          "Quantum Displacement"
        ]
      }
    },
    {
      "name": "Slipstream Generation",
      "description": "Movement particles generate slipstreams",
      "rarityTier": "Rare",
      "role": "MOVEMENT",
      "statType": "Slipstream",
      "bonusAmount": 30,
      "physicsLogic": {
        "forceMultiplier": 1.15,
        "rangeMultiplier": 1.1,
        "speedMultiplier": 1.3,
        "stabilityMultiplier": 1
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.75,
        "particleColor": "#99ccff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Displacement",
          "Hypersonic Velocity"
        ]
      }
    },
    {
      "name": "Quantum Displacement",
      "description": "Movement particles displace through quantum states",
      "rarityTier": "Epic",
      "role": "MOVEMENT",
      "statType": "Quantum",
      "bonusAmount": 35,
      "physicsLogic": {
        "forceMultiplier": 1.2,
        "rangeMultiplier": 1.15,
        "speedMultiplier": 1.35,
        "stabilityMultiplier": 0.95
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.7,
        "particleColor": "#aaddff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Hypersonic Velocity",
          "Temporal Phasing"
        ]
      }
    },
    {
      "name": "Hypersonic Velocity",
      "description": "Movement particles achieve hypersonic velocities",
      "rarityTier": "Epic",
      "role": "MOVEMENT",
      "statType": "Hypersonic",
      "bonusAmount": 40,
      "physicsLogic": {
        "forceMultiplier": 1.25,
        "rangeMultiplier": 1.2,
        "speedMultiplier": 1.4,
        "stabilityMultiplier": 0.9
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.65,
        "particleColor": "#bbeeff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Phasing",
          "Dimensional Slipstream"
        ]
      }
    },
    {
      "name": "Temporal Phasing",
      "description": "Movement particles phase through time",
      "rarityTier": "Legendary",
      "role": "MOVEMENT",
      "statType": "Temporal",
      "bonusAmount": 45,
      "physicsLogic": {
        "forceMultiplier": 1.3,
        "rangeMultiplier": 1.25,
        "speedMultiplier": 1.45,
        "stabilityMultiplier": 0.85
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.6,
        "particleColor": "#ccffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Slipstream",
          "Cosmic Velocity"
        ]
      }
    },
    {
      "name": "Dimensional Slipstream",
      "description": "Movement particles slip between dimensions",
      "rarityTier": "Legendary",
      "role": "MOVEMENT",
      "statType": "Dimensional",
      "bonusAmount": 50,
      "physicsLogic": {
        "forceMultiplier": 1.35,
        "rangeMultiplier": 1.3,
        "speedMultiplier": 1.5,
        "stabilityMultiplier": 0.8
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.55,
        "particleColor": "#ddffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity",
          "Reality Surfing"
        ]
      }
    },
    {
      "name": "Cosmic Velocity",
      "description": "Movement particles achieve cosmic velocities",
      "rarityTier": "Mythic",
      "role": "MOVEMENT",
      "statType": "Cosmic",
      "bonusAmount": 55,
      "physicsLogic": {
        "forceMultiplier": 1.4,
        "rangeMultiplier": 1.35,
        "speedMultiplier": 1.55,
        "stabilityMultiplier": 0.75
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.5,
        "particleColor": "#eeffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Surfing"
        ]
      }
    },
    {
      "name": "Reality Surfing",
      "description": "Movement particles surf between realities",
      "rarityTier": "Mythic",
      "role": "MOVEMENT",
      "statType": "Reality",
      "bonusAmount": 60,
      "physicsLogic": {
        "forceMultiplier": 1.45,
        "rangeMultiplier": 1.4,
        "speedMultiplier": 1.6,
        "stabilityMultiplier": 0.7
      },
      "visualEffects": {
        "particleGlow": true,
        "particleSize": 0.45,
        "particleColor": "#ffffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity"
        ]
      }
    }
  ];

export default MOVEMENT_CLASS_BONUS_TRAITS;





