// Generated from group_traits/trait_banks/force_calculation/movement_force_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { ForceCalculationTrait } from '../../../types/traits/trait';
import { Role, Rarity, ForceType, FalloffType } from '../../../types/core';

export const MOVEMENT_FORCE_CALCULATION_TRAITS = [
    {
      "name": "Fluid Dynamics",
      "description": "Particles move with fluid dynamic forces",
      "rarityTier": "Common",
      "type": "Alignment",
      "strengthMultiplier": 1.3,
      "rangeMultiplier": 1.4,
      "falloff": "linear",
      "physicsLogic": {
        "forceFunction": "fluidDynamics",
        "thresholdDistance": 3.5,
        "maxForce": 5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#3399ff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Streamlined Flow",
          "Aerodynamic Force"
        ]
      }
    },
    {
      "name": "Streamlined Flow",
      "description": "Particles align in streamlined flow patterns",
      "rarityTier": "Uncommon",
      "type": "Alignment",
      "strengthMultiplier": 1.4,
      "rangeMultiplier": 1.5,
      "falloff": "quadratic",
      "physicsLogic": {
        "forceFunction": "streamlinedFlow",
        "thresholdDistance": 3.7,
        "maxForce": 5.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#55aaff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Aerodynamic Force",
          "Vortex Dynamics"
        ]
      }
    },
    {
      "name": "Aerodynamic Force",
      "description": "Particles align with aerodynamic forces",
      "rarityTier": "Rare",
      "type": "Alignment",
      "strengthMultiplier": 1.5,
      "rangeMultiplier": 1.6,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "aerodynamicForce",
        "thresholdDistance": 3.9,
        "maxForce": 6
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#77bbff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex Dynamics",
          "Quantum Momentum"
        ]
      }
    },
    {
      "name": "Vortex Dynamics",
      "description": "Particles align in vortex patterns",
      "rarityTier": "Rare",
      "type": "Alignment",
      "strengthMultiplier": 1.6,
      "rangeMultiplier": 1.7,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "vortexDynamics",
        "thresholdDistance": 4.1,
        "maxForce": 6.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#99ccff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Momentum",
          "Slipstream Dynamics"
        ]
      }
    },
    {
      "name": "Quantum Momentum",
      "description": "Particles align with quantum momentum",
      "rarityTier": "Epic",
      "type": "Alignment",
      "strengthMultiplier": 1.7,
      "rangeMultiplier": 1.8,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "quantumMomentum",
        "thresholdDistance": 4.3,
        "maxForce": 7
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#aaddff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Slipstream Dynamics",
          "Temporal Velocity"
        ]
      }
    },
    {
      "name": "Slipstream Dynamics",
      "description": "Particles align in efficient slipstreams",
      "rarityTier": "Epic",
      "type": "Alignment",
      "strengthMultiplier": 1.8,
      "rangeMultiplier": 1.9,
      "falloff": "exponential",
      "physicsLogic": {
        "forceFunction": "slipstreamDynamics",
        "thresholdDistance": 4.5,
        "maxForce": 7.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#bbeeff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Velocity",
          "Dimensional Slipstream"
        ]
      }
    },
    {
      "name": "Temporal Velocity",
      "description": "Particles align with temporal velocity",
      "rarityTier": "Legendary",
      "type": "Alignment",
      "strengthMultiplier": 1.9,
      "rangeMultiplier": 2,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "temporalVelocity",
        "thresholdDistance": 4.7,
        "maxForce": 8
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ccffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Slipstream",
          "Cosmic Velocity"
        ]
      }
    },
    {
      "name": "Dimensional Slipstream",
      "description": "Particles align across dimensional slipstreams",
      "rarityTier": "Legendary",
      "type": "Alignment",
      "strengthMultiplier": 2,
      "rangeMultiplier": 2.1,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "dimensionalSlipstream",
        "thresholdDistance": 4.9,
        "maxForce": 8.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ddffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity",
          "Reality Surfing"
        ]
      }
    },
    {
      "name": "Cosmic Velocity",
      "description": "Particles align with cosmic-scale velocities",
      "rarityTier": "Mythic",
      "type": "Alignment",
      "strengthMultiplier": 2.1,
      "rangeMultiplier": 2.2,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "cosmicVelocity",
        "thresholdDistance": 5.1,
        "maxForce": 9
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#eeffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Reality Surfing"
        ]
      }
    },
    {
      "name": "Reality Surfing",
      "description": "Particles align to surf between realities",
      "rarityTier": "Mythic",
      "type": "Alignment",
      "strengthMultiplier": 2.2,
      "rangeMultiplier": 2.3,
      "falloff": "quantum",
      "physicsLogic": {
        "forceFunction": "realitySurfing",
        "thresholdDistance": 5.3,
        "maxForce": 9.5
      },
      "visualEffects": {
        "forceVisualization": true,
        "forceColor": "#ffffff"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity"
        ]
      }
    }
  ];

export default MOVEMENT_FORCE_CALCULATION_TRAITS;





