// Generated from group_traits/trait_banks/subclass/movement_subclass_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { SubclassTrait } from '../../../types/traits/trait';
import { Role, Rarity, AbilityType } from '../../../types/core';

export const MOVEMENT_SUBCLASS_TRAITS = [
    {
      "name": "Swift Runner",
      "description": "A movement specialist focused on speed",
      "rarityTier": "Common",
      "role": "MOVEMENT",
      "formationTrait": "Stream Formation",
      "abilities": [
        {
          "name": "Acceleration",
          "description": "Rapidly increases movement speed",
          "type": "Primary",
          "cooldown": 4,
          "physicsLogic": {
            "forceMultiplier": 1.4,
            "rangeMultiplier": 1,
            "durationSeconds": 3
          },
          "visualEffects": {
            "particleEffect": "speed_trail",
            "areaEffect": "none",
            "colorFlash": "#3399ff"
          }
        },
        {
          "name": "Momentum",
          "description": "Builds and maintains momentum for sustained speed",
          "type": "Secondary",
          "cooldown": 7,
          "physicsLogic": {
            "forceMultiplier": 1.3,
            "rangeMultiplier": 1.1,
            "durationSeconds": 5
          },
          "visualEffects": {
            "particleEffect": "momentum_streak",
            "areaEffect": "speed_field",
            "colorFlash": "#55aaff"
          }
        }
      ],
      "synergy": "Works well with Attack subclasses for hit-and-run tactics",
      "themeProperties": {
        "primaryColor": "#3399ff",
        "secondaryColor": "#55aaff",
        "particleEffect": "speed_blur",
        "soundEffect": "swift_whoosh"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Slipstreamer",
          "Vortex Dancer"
        ]
      }
    },
    {
      "name": "Slipstreamer",
      "description": "A movement specialist that creates and utilizes slipstreams",
      "rarityTier": "Uncommon",
      "role": "MOVEMENT",
      "formationTrait": "Wave Pattern",
      "abilities": [
        {
          "name": "Slipstream Creation",
          "description": "Creates a slipstream for efficient movement",
          "type": "Primary",
          "cooldown": 6,
          "physicsLogic": {
            "forceMultiplier": 1.2,
            "rangeMultiplier": 1.6,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "slipstream_trail",
            "areaEffect": "flow_channel",
            "colorFlash": "#77bbff"
          }
        },
        {
          "name": "Aerodynamic Shift",
          "description": "Alters form for maximum aerodynamic efficiency",
          "type": "Secondary",
          "cooldown": 9,
          "physicsLogic": {
            "forceMultiplier": 1.3,
            "rangeMultiplier": 1.2,
            "durationSeconds": 6
          },
          "visualEffects": {
            "particleEffect": "streamlined_form",
            "areaEffect": "air_current",
            "colorFlash": "#99ccff"
          }
        }
      ],
      "synergy": "Works well with Control subclasses for coordinated movement",
      "themeProperties": {
        "primaryColor": "#77bbff",
        "secondaryColor": "#99ccff",
        "particleEffect": "slipstream_shimmer",
        "soundEffect": "air_rush"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex Dancer",
          "Quantum Leaper"
        ]
      }
    },
    {
      "name": "Vortex Dancer",
      "description": "A movement specialist that manipulates vortices for mobility",
      "rarityTier": "Rare",
      "role": "MOVEMENT",
      "formationTrait": "Vortex Flow",
      "abilities": [
        {
          "name": "Vortex Creation",
          "description": "Creates a vortex for rapid movement",
          "type": "Primary",
          "cooldown": 7,
          "physicsLogic": {
            "forceMultiplier": 1.5,
            "rangeMultiplier": 1.4,
            "durationSeconds": 4
          },
          "visualEffects": {
            "particleEffect": "vortex_spiral",
            "areaEffect": "spinning_current",
            "colorFlash": "#aaddff"
          }
        },
        {
          "name": "Cyclonic Propulsion",
          "description": "Uses cyclonic forces for powerful bursts of speed",
          "type": "Secondary",
          "cooldown": 10,
          "physicsLogic": {
            "forceMultiplier": 1.7,
            "rangeMultiplier": 1.3,
            "durationSeconds": 3
          },
          "visualEffects": {
            "particleEffect": "cyclone_trail",
            "areaEffect": "spiral_wake",
            "colorFlash": "#bbeeff"
          }
        }
      ],
      "synergy": "Works well with Defense subclasses for mobile defense",
      "themeProperties": {
        "primaryColor": "#aaddff",
        "secondaryColor": "#bbeeff",
        "particleEffect": "vortex_glow",
        "soundEffect": "cyclonic_spin"
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Leaper",
          "Temporal Surfer"
        ]
      }
    }
  ];

export default MOVEMENT_SUBCLASS_TRAITS;





