// Generated from group_traits/trait_banks/visual/movement_visual_traits.json
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_trait_data_better.ps1

import { VisualTrait } from '../../../types/traits/trait';
import { Role, Rarity } from '../../../types/core';

export const MOVEMENT_VISUAL_TRAITS: VisualTrait[] = [
    {
      "id": "movement_visual_streamlined",
      "name": "Streamlined",
      "description": "A streamlined structure that leaves a speed trail",
      "shape": "Streamlined",
      "colorScheme": "Blue Gradient",
      "visualEffect": "Speed Trail",
      "rarityTier": Rarity.COMMON,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomStreamlinedGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.8,
        "emissive": false,
        "opacity": 1,
        "colorHex": "#3399ff"
      },
      "animationProperties": {
        "pulseRate": 0,
        "rotationSpeed": 0,
        "trailLength": 1
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Wave Form",
          "Aerodynamic"
        ]
      }
    },
    {
      "id": "movement_visual_wave_form",
      "name": "Wave Form",
      "description": "A wave form structure that oscillates with azure energy",
      "shape": "Wave Form",
      "colorScheme": "Azure",
      "visualEffect": "Oscillating Trail",
      "rarityTier": Rarity.UNCOMMON,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomWaveGeometry",
        "material": "MeshStandardMaterial",
        "scale": 0.75,
        "emissive": true,
        "opacity": 0.95,
        "colorHex": "#55aaff"
      },
      "animationProperties": {
        "pulseRate": 0.3,
        "rotationSpeed": 0,
        "trailLength": 1.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Aerodynamic",
          "Slipstream"
        ]
      }
    },
    {
      "id": "movement_visual_aerodynamic",
      "name": "Aerodynamic",
      "description": "An aerodynamic structure that creates air currents with cerulean energy",
      "shape": "Aerodynamic",
      "colorScheme": "Cerulean",
      "visualEffect": "Air Current",
      "rarityTier": Rarity.RARE,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomAerodynamicGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.7,
        "emissive": true,
        "opacity": 0.9,
        "colorHex": "#77bbff"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.1,
        "trailLength": 2
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Slipstream",
          "Vortex"
        ]
      }
    },
    {
      "id": "movement_visual_slipstream",
      "name": "Slipstream",
      "description": "A slipstream structure that creates flow channels with sky blue energy",
      "shape": "Slipstream",
      "colorScheme": "Sky Blue",
      "visualEffect": "Flow Channel",
      "rarityTier": Rarity.RARE,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomSlipstreamGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.65,
        "emissive": true,
        "opacity": 0.85,
        "colorHex": "#99ccff"
      },
      "animationProperties": {
        "pulseRate": 0.1,
        "rotationSpeed": 0.2,
        "trailLength": 2.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Vortex",
          "Quantum Leap"
        ]
      }
    },
    {
      "id": "movement_visual_vortex",
      "name": "Vortex",
      "description": "A vortex structure that creates spiral flows with cobalt energy",
      "shape": "Vortex",
      "colorScheme": "Cobalt",
      "visualEffect": "Spiral Flow",
      "rarityTier": Rarity.EPIC,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomVortexGeometry",
        "material": "MeshPhysicalMaterial",
        "scale": 0.6,
        "emissive": true,
        "opacity": 0.8,
        "colorHex": "#aaddff"
      },
      "animationProperties": {
        "pulseRate": 0.4,
        "rotationSpeed": 0.5,
        "trailLength": 3
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Leap",
          "Hypersonic"
        ]
      }
    },
    {
      "id": "movement_visual_hypersonic",
      "name": "Hypersonic",
      "description": "A hypersonic structure that creates shock waves with electric blue energy",
      "shape": "Hypersonic",
      "colorScheme": "Electric Blue",
      "visualEffect": "Shock Wave",
      "rarityTier": Rarity.EPIC,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomHypersonicGeometry",
        "material": "ShaderMaterial",
        "scale": 0.55,
        "emissive": true,
        "opacity": 0.75,
        "colorHex": "#bbeeff"
      },
      "animationProperties": {
        "pulseRate": 0.2,
        "rotationSpeed": 0.3,
        "trailLength": 3.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Quantum Leap",
          "Temporal Slip"
        ]
      }
    },
    {
      "id": "movement_visual_quantum_leap",
      "name": "Quantum Leap",
      "description": "A quantum leap structure that creates probability trails with quantum blue energy",
      "shape": "Quantum Leap",
      "colorScheme": "Quantum Blue",
      "visualEffect": "Probability Trail",
      "rarityTier": Rarity.LEGENDARY,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomQuantumGeometry",
        "material": "ShaderMaterial",
        "scale": 0.5,
        "emissive": true,
        "opacity": 0.7,
        "colorHex": "#ccffff"
      },
      "animationProperties": {
        "pulseRate": 0.5,
        "rotationSpeed": 0,
        "trailLength": 4
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Temporal Slip",
          "Dimensional Shift"
        ]
      }
    },
    {
      "id": "movement_visual_temporal_slip",
      "name": "Temporal Slip",
      "description": "A temporal slip structure that creates time echoes with chrono blue energy",
      "shape": "Temporal Slip",
      "colorScheme": "Chrono Blue",
      "visualEffect": "Time Echo",
      "rarityTier": Rarity.LEGENDARY,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomTemporalGeometry",
        "material": "ShaderMaterial",
        "scale": 0.45,
        "emissive": true,
        "opacity": 0.65,
        "colorHex": "#ddffff"
      },
      "animationProperties": {
        "pulseRate": 0.6,
        "rotationSpeed": 0.1,
        "trailLength": 4.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Dimensional Shift",
          "Cosmic Velocity"
        ]
      }
    },
    {
      "id": "movement_visual_dimensional_shift",
      "name": "Dimensional Shift",
      "description": "A dimensional shift structure that blurs reality with ethereal blue energy",
      "shape": "Dimensional Shift",
      "colorScheme": "Ethereal Blue",
      "visualEffect": "Reality Blur",
      "rarityTier": Rarity.MYTHIC,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomDimensionalGeometry",
        "material": "ShaderMaterial",
        "scale": 0.4,
        "emissive": true,
        "opacity": 0.6,
        "colorHex": "#eeffff"
      },
      "animationProperties": {
        "pulseRate": 0.7,
        "rotationSpeed": 0.2,
        "trailLength": 5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity",
          "Reality Surfer"
        ]
      }
    },
    {
      "id": "movement_visual_reality_surfer",
      "name": "Reality Surfer",
      "description": "A reality surfer structure that creates multiverse wakes with cosmic blue energy",
      "shape": "Reality Surfer",
      "colorScheme": "Cosmic Blue",
      "visualEffect": "Multiverse Wake",
      "rarityTier": Rarity.MYTHIC,
      "role": Role.MOVEMENT,
      "renderingProperties": {
        "geometry": "CustomRealitySurferGeometry",
        "material": "ShaderMaterial",
        "scale": 0.35,
        "emissive": true,
        "opacity": 0.55,
        "colorHex": "#ffffff"
      },
      "animationProperties": {
        "pulseRate": 0.8,
        "rotationSpeed": 0.3,
        "trailLength": 5.5
      },
      "evolutionParameters": {
        "mutationChance": 0.05,
        "possibleEvolutions": [
          "Cosmic Velocity",
          "Dimensional Shift"
        ]
      }
    }
  ];

export default MOVEMENT_VISUAL_TRAITS;





